function [DecNext, info] = DAREMO_Infill(DecArchive, ObjArchive, lower, upper, batchSize, config, generations)
%DAREMO_INFILL Difficulty-aware relation-model infill selector for PlatEMO.
%
%   [DecNext, info] = DAREMO_Infill(DecArchive, ObjArchive, lower, upper, batchSize)
%   proposes batchSize new decision vectors for expensive evaluation.
%
%   Inputs:
%       DecArchive  - N-by-D evaluated decision matrix, e.g. Population.decs
%       ObjArchive  - N-by-M objective matrix, minimization, e.g. Population.objs
%       lower       - 1-by-D lower bound, e.g. Problem.lower
%       upper       - 1-by-D upper bound, e.g. Problem.upper
%       batchSize   - number of candidates to return
%       config      - optional struct. Missing fields use defaults.
%       generations - optional N-by-1 generation index for progress difficulty.
%
%   Output:
%       DecNext     - batchSize-by-D decision matrix to be evaluated by Problem.Evaluation
%       info        - diagnostic struct: difficulty, subsets, experts, scores, etc.
%
%   Main idea:
%       1) estimate objective-wise online difficulty;
%       2) sort objectives from easy to hard;
%       3) build prefix sub-objective relation models plus a full-objective model;
%       4) fuse relation predictions with reliability, uncertainty, novelty, and conflict penalty.
%
%   This file is self-contained. It preferentially uses TreeBagger when available.
%   If TreeBagger is unavailable, it falls back to a pure-MATLAB weighted kNN relation model.
%
%   Labels used internally:
%       0: first solution is better
%       1: second solution is better
%       2: non-comparable / tie
%
%   Author: generated by ChatGPT for research prototyping.

    if nargin < 5 || isempty(batchSize), batchSize = 1; end
    if nargin < 6 || isempty(config), config = struct(); end
    if nargin < 7, generations = []; end

    cfg = DA_DefaultConfig(config);
    rng(cfg.RandomState);

    X = double(DecArchive);
    F = double(ObjArchive);
    lower = double(lower(:)');
    upper = double(upper(:)');

    if size(X,1) ~= size(F,1)
        error('DecArchive and ObjArchive must have the same number of rows.');
    end
    if size(X,2) ~= numel(lower) || numel(lower) ~= numel(upper)
        error('Dimension mismatch between DecArchive, lower, and upper.');
    end

    [N, D] = size(X);
    M = size(F,2);

    if N < 6
        DecNext = repmat(lower,batchSize,1) + rand(batchSize,D).*repmat(upper-lower,batchSize,1);
        info = struct();
        info.reason = 'too_few_archive_points';
        return;
    end

    difficulty = DA_EstimateDifficulty(X, F, generations, cfg);
    subsets    = DA_BuildSubsets(M, difficulty.orderEasyToHard, cfg);
    experts    = DA_TrainExperts(X, F, subsets, cfg);

    if isempty(experts)
        DecNext = repmat(lower,batchSize,1) + rand(batchSize,D).*repmat(upper-lower,batchSize,1);
        info = struct();
        info.reason = 'no_experts_trained';
        info.difficulty = difficulty;
        info.subsets = subsets;
        return;
    end

    Cand = DA_GenerateCandidates(X, lower, upper, cfg.NCandidates, cfg);
    [score, scoreInfo] = DA_ScoreCandidates(Cand, X, F, lower, upper, experts, cfg);
    chosen = DA_GreedyDiverseSelection(Cand, score, batchSize, lower, upper, cfg);

    DecNext = Cand(chosen,:);

    info = struct();
    info.difficulty      = difficulty;
    info.subsets         = subsets;
    info.experts         = experts;
    info.scores          = score;
    info.chosenIndices   = chosen;
    info.candidatePool   = Cand;
    info.expertScores    = scoreInfo.expertScores;
    info.expertUncertainty = scoreInfo.expertUncertainty;
    info.expertWeights   = scoreInfo.expertWeights;
    info.meanScore       = scoreInfo.meanScore;
    info.uncertainty     = scoreInfo.uncertainty;
    info.disagreement    = scoreInfo.disagreement;
    info.novelty         = scoreInfo.novelty;
    info.anchors         = scoreInfo.anchors;
end

%% ------------------------------------------------------------------------
function cfg = DA_DefaultConfig(userCfg)
    cfg = struct();

    % Pair generation and PBI labels.
    cfg.MaxPairs       = 5000;
    cfg.PBITheta       = 5.0;
    cfg.PBIMargin      = 1e-4;
    cfg.NRefVectors    = 80;
    cfg.MaxSubmodels   = 4;
    cfg.MinSubsetSize  = 2;
    cfg.RandomState    = 1;

    % Relation classifier.
    cfg.RFTrees        = 160;
    cfg.RFMinLeaf      = 2;
    cfg.ValidationSize = 0.25;
    cfg.KNNK           = 15;       % fallback classifier if TreeBagger is unavailable
    cfg.KNNMaxTrain    = 6000;     % cap fallback training pairs for speed
    cfg.UseTreeBagger  = true;

    % Candidate generation/scoring.
    cfg.NCandidates    = 1000;
    cfg.DEFactor       = 0.5;
    cfg.MutationEta    = 20;
    cfg.MutationProb   = [];       % default: 1/D
    cfg.AnchorSize     = 60;
    cfg.UncertaintyWeight = 0.15;
    cfg.NoveltyWeight     = 0.05;
    cfg.ConflictPenalty   = 0.10;
    cfg.FullModelMinWeight = 0.35;
    cfg.DiversityGreedyWeight = 0.2;

    if nargin > 0 && ~isempty(userCfg)
        names = fieldnames(userCfg);
        for i = 1:numel(names)
            cfg.(names{i}) = userCfg.(names{i});
        end
    end
end

%% ------------------------------------------------------------------------
function difficulty = DA_EstimateDifficulty(X, F, generations, cfg)
    [N, M] = size(F);
    [Fn, ~, ~] = DA_NormalizeObjectives(F);

    % 1) Progress difficulty: little recent improvement => harder.
    window = 20;
    if ~isempty(generations)
        generations = generations(:);
        ug = unique(generations);
        if numel(ug) >= 2
            cut = ug(max(1, numel(ug)-window+1));
            recentMask = generations >= cut;
            prevMask = generations < cut;
            if sum(prevMask) < 3, prevMask = true(N,1); end
        else
            recentMask = (1:N)' >= max(1,N-window+1);
            prevMask = (1:N)' < max(1,N-window+1);
        end
    else
        recentMask = (1:N)' >= max(1,N-window+1);
        prevMask = (1:N)' < max(1,N-window+1);
        if sum(prevMask) < 3, prevMask = true(N,1); end
    end
    if sum(recentMask) < 1, recentMask = true(N,1); end

    qPrev   = prctile(Fn(prevMask,:),20,1);
    qRecent = prctile(Fn(recentMask,:),20,1);
    improvement = max(0, qPrev - qRecent);
    posImp = improvement(improvement > 0);
    if isempty(posImp), scale = 1; else, scale = median(posImp); end
    progress = 1 ./ (1 + improvement./(scale+1e-12));

    % 2) Relation learnability/error per single objective.
    relationError = zeros(1,M);
    for j = 1:M
        try
            [Phi, y, ~] = DA_MakePairDataset(X, Fn, j, min(cfg.MaxPairs,2000), cfg.PBITheta, cfg.PBIMargin, 3, true);
            if numel(unique(y)) < 2 || numel(y) < 20
                relationError(j) = 0.5;
            else
                [tr, va] = DA_TrainValSplit(y, cfg.ValidationSize);
                model = DA_TrainRelationModel(Phi(tr,:), y(tr), cfg, true);
                pred = DA_PredictClass(model, Phi(va,:));
                acc = DA_BalancedAccuracy(y(va), pred);
                relationError(j) = 1 - min(max(acc,0),1);
            end
        catch ME
            warning('DAREMO:DifficultyRelationError', 'Relation-error failed for objective %d: %s', j, ME.message);
            relationError(j) = 0.5;
        end
    end

    % 3) Conflict: negative correlations with other objectives.
    C = corrcoef(Fn);
    C(isnan(C)) = 0;
    conflict = zeros(1,M);
    for j = 1:M
        others = setdiff(1:M,j);
        if ~isempty(others)
            conflict(j) = mean(max(0,-C(j,others)));
        end
    end
    if max(conflict) > 0
        conflict = conflict ./ max(conflict);
    end

    % 4) Sensitivity: relation labels changed when objective j is removed.
    sensitivity = zeros(1,M);
    if M >= 2 && N >= 5
        Wfull = DA_RandomReferenceVectors(M, min(cfg.NRefVectors,100));
        targetPairs = min(1000, N*(N-1)/2);
        pairs = DA_SamplePairs(N, targetPairs);
        fullLabels = zeros(size(pairs,1),1);
        for p = 1:size(pairs,1)
            i = pairs(p,1); k = pairs(p,2);
            fullLabels(p) = DA_PBIRelationLabel(Fn(i,:), Fn(k,:), Wfull, cfg.PBITheta, cfg.PBIMargin);
        end
        for j = 1:M
            subset = setdiff(1:M,j);
            Wsub = DA_RandomReferenceVectors(numel(subset), min(cfg.NRefVectors,100));
            subLabels = zeros(size(pairs,1),1);
            for p = 1:size(pairs,1)
                i = pairs(p,1); k = pairs(p,2);
                subLabels(p) = DA_PBIRelationLabel(Fn(i,subset), Fn(k,subset), Wsub, cfg.PBITheta, cfg.PBIMargin);
            end
            sensitivity(j) = mean(fullLabels ~= subLabels);
        end
        if max(sensitivity) > 0
            sensitivity = sensitivity ./ max(sensitivity);
        end
    end

    % 5) Weak robust relative span signal.
    relSpan = zeros(1,M);
    for j = 1:M
        relSpan(j) = DA_RobustRelativeSpan(F(:,j));
    end
    if max(relSpan) > min(relSpan)
        relSpan = (relSpan - min(relSpan)) ./ (max(relSpan)-min(relSpan)+1e-12);
    else
        relSpan(:) = 0;
    end

    total = 0.35*progress + 0.25*relationError + 0.20*conflict + 0.15*sensitivity + 0.05*relSpan;
    [~, order] = sort(total, 'ascend');

    difficulty = struct();
    difficulty.total = total;
    difficulty.progress = progress;
    difficulty.relationError = relationError;
    difficulty.conflict = conflict;
    difficulty.sensitivity = sensitivity;
    difficulty.relativeSpan = relSpan;
    difficulty.orderEasyToHard = order;
end

%% ------------------------------------------------------------------------
function subsets = DA_BuildSubsets(M, orderEasyToHard, cfg)
    minK = min(max(1,cfg.MinSubsetSize), M);
    if M <= minK
        subsets = {1:M};
        return;
    end

    nSub = min(cfg.MaxSubmodels, max(1,M-1));
    sizes = unique(round(linspace(minK, M-1, nSub)));
    subsets = cell(1,numel(sizes)+1);
    cnt = 0;
    for i = 1:numel(sizes)
        k = sizes(i);
        cnt = cnt + 1;
        subsets{cnt} = orderEasyToHard(1:k);
    end
    full = 1:M;
    hasFull = false;
    for i = 1:cnt
        if numel(subsets{i}) == M && all(sort(subsets{i}) == full)
            hasFull = true;
            break;
        end
    end
    if ~hasFull
        cnt = cnt + 1;
        subsets{cnt} = full;
    end
    subsets = subsets(1:cnt);
end

%% ------------------------------------------------------------------------
function experts = DA_TrainExperts(X, F, subsets, cfg)
    [Fn, ~, ~] = DA_NormalizeObjectives(F);
    M = size(F,2);
    experts = struct('subset',{},'name',{},'model',{},'reliability',{},'W',{},'labelCounts',{});

    for s = 1:numel(subsets)
        subset = subsets{s};
        [Phi, y, W] = DA_MakePairDataset(X, Fn, subset, cfg.MaxPairs, cfg.PBITheta, cfg.PBIMargin, min(cfg.NRefVectors,max(10,4*numel(subset))), true);
        counts = [sum(y==0), sum(y==1), sum(y==2)];
        if numel(unique(y)) < 2
            warning('DAREMO:DegenerateSubset', 'Skipping subset because it has only one relation class.');
            continue;
        end

        [tr, va] = DA_TrainValSplit(y, cfg.ValidationSize);
        model = DA_TrainRelationModel(Phi(tr,:), y(tr), cfg, false);
        pred = DA_PredictClass(model, Phi(va,:));
        acc = DA_BalancedAccuracy(y(va), pred);
        reliability = min(max((acc - 1/3)/(2/3), 0), 1);

        e = struct();
        e.subset = subset;
        if numel(subset) == M && all(sort(subset) == 1:M)
            e.name = 'full';
        else
            e.name = ['sub_' sprintf('%d_',subset)];
            if e.name(end) == '_', e.name(end) = []; end
        end
        e.model = model;
        e.reliability = reliability;
        e.W = W;
        e.labelCounts = counts;
        experts(end+1) = e; %#ok<AGROW>
    end
end

%% ------------------------------------------------------------------------
function [score, info] = DA_ScoreCandidates(Cand, X, F, lower, upper, experts, cfg)
    nC = size(Cand,1);
    D  = size(Cand,2);
    M  = size(F,2);
    anchors = DA_SelectAnchors(X, F, cfg);
    A = X(anchors,:);
    nA = size(A,1);
    weights = DA_ExpertWeights(experts, M, cfg);

    E = numel(experts);
    expertScores = zeros(E,nC);
    expertUnc    = zeros(E,nC);

    % Build candidate-anchor pair features once.
    PhiAll = zeros(nC*nA, 2*D);
    pos = 1;
    for c = 1:nC
        rows = pos:(pos+nA-1);
        PhiAll(rows,:) = DA_PairFeatures(repmat(Cand(c,:),nA,1), A);
        pos = pos + nA;
    end

    for e = 1:E
        P = DA_PredictProba3(experts(e).model, PhiAll);
        winLoss = P(:,1) - P(:,2);
        ent = -sum(P .* log(max(P,1e-12)),2) ./ log(3);
        expertScores(e,:) = mean(reshape(winLoss,nA,nC),1);
        expertUnc(e,:)    = mean(reshape(ent,nA,nC),1);
    end

    meanScore = weights(:)' * expertScores;
    uncertainty = weights(:)' * expertUnc;
    disagreement = zeros(1,nC);
    for e = 1:E
        disagreement = disagreement + weights(e) .* (expertScores(e,:) - meanScore).^2;
    end

    diagLen = norm(upper-lower) + 1e-12;
    novelty = zeros(1,nC);
    chunk = 512;
    for st = 1:chunk:nC
        ed = min(nC, st+chunk-1);
        Dist = DA_SquaredDistance(Cand(st:ed,:), X);
        novelty(st:ed) = sqrt(min(Dist,[],2))' ./ diagLen;
    end

    score = meanScore + cfg.UncertaintyWeight*uncertainty + cfg.NoveltyWeight*novelty - cfg.ConflictPenalty*disagreement;

    info = struct();
    info.expertScores = expertScores;
    info.expertUncertainty = expertUnc;
    info.expertWeights = weights;
    info.meanScore = meanScore;
    info.uncertainty = uncertainty;
    info.disagreement = disagreement;
    info.novelty = novelty;
    info.anchors = anchors;
end

%% ------------------------------------------------------------------------
function chosen = DA_GreedyDiverseSelection(Cand, score, batchSize, lower, upper, cfg)
    nC = size(Cand,1);
    batchSize = min(batchSize,nC);
    chosen = zeros(1,batchSize);
    remaining = true(1,nC);
    diagLen = norm(upper-lower) + 1e-12;
    s = (score - min(score)) ./ (max(score)-min(score)+1e-12);

    for t = 1:batchSize
        rem = find(remaining);
        if t == 1
            [~,idx] = max(s(rem));
            pick = rem(idx);
        else
            Dist = DA_SquaredDistance(Cand(rem,:), Cand(chosen(1:t-1),:));
            dmin = sqrt(min(Dist,[],2))' ./ diagLen;
            merit = s(rem) + cfg.DiversityGreedyWeight*dmin;
            [~,idx] = max(merit);
            pick = rem(idx);
        end
        chosen(t) = pick;
        remaining(pick) = false;
    end
    chosen = chosen(:);
end

%% ------------------------------------------------------------------------
function weights = DA_ExpertWeights(experts, M, cfg)
    E = numel(experts);
    rel = zeros(1,E);
    for e = 1:E, rel(e) = experts(e).reliability; end
    weights = exp(3*(rel - max(rel)));
    weights = weights ./ sum(weights);

    fullIdx = [];
    for e = 1:E
        if numel(experts(e).subset) == M && all(sort(experts(e).subset) == 1:M)
            fullIdx = e;
            break;
        end
    end
    if ~isempty(fullIdx)
        minw = min(cfg.FullModelMinWeight, 0.8);
        if weights(fullIdx) < minw
            otherSum = max(1e-12, 1 - weights(fullIdx));
            weights = weights .* (1-minw) ./ otherSum;
            weights(fullIdx) = minw;
        end
    end
    weights = weights ./ sum(weights);
end

%% ------------------------------------------------------------------------
function anchors = DA_SelectAnchors(X, F, cfg)
    [Fn, ~, ~] = DA_NormalizeObjectives(F);
    nd = DA_ParetoFrontMask(Fn);
    candidates = find(nd);
    if isempty(candidates), candidates = 1:size(X,1); end

    if numel(candidates) > cfg.AnchorSize
        [~,bestLocal] = min(sum(Fn(candidates,:),2));
        selected = candidates(bestLocal);
        remaining = setdiff(candidates, selected);
        while numel(selected) < cfg.AnchorSize && ~isempty(remaining)
            Dist = DA_SquaredDistance(Fn(remaining,:), Fn(selected,:));
            [~,idx] = max(min(Dist,[],2));
            selected(end+1) = remaining(idx); %#ok<AGROW>
            remaining(idx) = [];
        end
        candidates = selected;
    end
    anchors = candidates(:);
end

%% ------------------------------------------------------------------------
function Cand = DA_GenerateCandidates(X, lower, upper, nCandidates, cfg)
    [N,D] = size(X);
    nDE = floor(0.75*nCandidates);
    nRand = nCandidates - nDE;

    if N < 4
        C1 = repmat(lower,nDE,1) + rand(nDE,D).*repmat(upper-lower,nDE,1);
    else
        idx = zeros(nDE,3);
        for i = 1:nDE
            row = randi(N,1,3);
            tries = 0;
            while numel(unique(row)) < 3 && tries < 10
                row = randi(N,1,3);
                tries = tries + 1;
            end
            idx(i,:) = row;
        end
        C1 = X(idx(:,1),:) + cfg.DEFactor .* (X(idx(:,2),:) - X(idx(:,3),:));
        C1 = min(max(C1, repmat(lower,nDE,1)), repmat(upper,nDE,1));
    end

    if nRand > 0
        C2 = repmat(lower,nRand,1) + rand(nRand,D).*repmat(upper-lower,nRand,1);
        Cand = [C1; C2];
    else
        Cand = C1;
    end
    Cand = DA_PolyMutation(Cand, lower, upper, cfg);
    Cand = min(max(Cand, repmat(lower,size(Cand,1),1)), repmat(upper,size(Cand,1),1));
end

%% ------------------------------------------------------------------------
function Y = DA_PolyMutation(X, lower, upper, cfg)
    Y = X;
    [N,D] = size(Y);
    if isempty(cfg.MutationProb)
        pm = 1/D;
    else
        pm = cfg.MutationProb;
    end
    eta = cfg.MutationEta;
    for i = 1:N
        for j = 1:D
            if rand > pm, continue; end
            y = Y(i,j); yl = lower(j); yu = upper(j);
            if yu <= yl, continue; end
            delta1 = (y-yl)/(yu-yl);
            delta2 = (yu-y)/(yu-yl);
            rnd = rand;
            mutPow = 1/(eta+1);
            if rnd <= 0.5
                xy = 1 - delta1;
                val = 2*rnd + (1-2*rnd)*(xy^(eta+1));
                deltaq = val^mutPow - 1;
            else
                xy = 1 - delta2;
                val = 2*(1-rnd) + 2*(rnd-0.5)*(xy^(eta+1));
                deltaq = 1 - val^mutPow;
            end
            y = y + deltaq*(yu-yl);
            Y(i,j) = min(max(y,yl),yu);
        end
    end
end

%% ------------------------------------------------------------------------
function [Phi, y, W] = DA_MakePairDataset(X, Fn, subset, maxPairs, theta, margin, nRefVectors, balance)
    N = size(X,1);
    subset = subset(:)';
    if N < 2, error('Need at least two evaluated solutions.'); end
    if nargin < 8 || isempty(nRefVectors)
        nRefVectors = min(100, max(10, 3*numel(subset)));
    end
    if nargin < 9, balance = true; end

    W = DA_RandomReferenceVectors(numel(subset), nRefVectors);
    totalPairs = N*(N-1)/2;
    k = min(maxPairs,totalPairs);
    pairs = DA_SamplePairs(N,k);

    Phi = zeros(2*size(pairs,1), 2*size(X,2));
    y   = zeros(2*size(pairs,1), 1);
    pos = 1;
    for p = 1:size(pairs,1)
        i = pairs(p,1); j = pairs(p,2);
        fa = Fn(i,subset); fb = Fn(j,subset);
        lab = DA_PBIRelationLabel(fa,fb,W,theta,margin);
        Phi(pos,:) = DA_PairFeatures(X(i,:),X(j,:));
        y(pos) = lab;
        pos = pos + 1;

        if lab == 0
            rev = 1;
        elseif lab == 1
            rev = 0;
        else
            rev = 2;
        end
        Phi(pos,:) = DA_PairFeatures(X(j,:),X(i,:));
        y(pos) = rev;
        pos = pos + 1;
    end

    if balance && numel(unique(y)) > 1
        keep = [];
        counts = [sum(y==0), sum(y==1), sum(y==2)];
        nonzero = counts(counts>0);
        target = round(median(nonzero));
        target = max(target, min(200,numel(y)));
        target = min(target, max(nonzero));
        for cls = 0:2
            idx = find(y==cls);
            if isempty(idx), continue; end
            if numel(idx) > target
                idx = idx(randperm(numel(idx),target));
            end
            keep = [keep; idx(:)]; %#ok<AGROW>
        end
        keep = keep(randperm(numel(keep)));
        Phi = Phi(keep,:);
        y = y(keep);
    end
end

%% ------------------------------------------------------------------------
function pairs = DA_SamplePairs(N, k)
    totalPairs = N*(N-1)/2;
    k = min(k,totalPairs);
    if k == totalPairs
        [I,J] = find(triu(true(N),1));
        pairs = [I,J];
    else
        pairs = zeros(k,2);
        used = false(N,N);
        cnt = 0;
        while cnt < k
            i = randi(N); j = randi(N);
            if i == j, continue; end
            if i > j, tmp = i; i = j; j = tmp; end
            if used(i,j), continue; end
            cnt = cnt + 1;
            used(i,j) = true;
            pairs(cnt,:) = [i,j];
        end
    end
end

%% ------------------------------------------------------------------------
function model = DA_TrainRelationModel(Phi, y, cfg, smallModel)
    if nargin < 4, smallModel = false; end
    useTree = cfg.UseTreeBagger && exist('TreeBagger','file') == 2;

    if useTree
        try
            nTrees = cfg.RFTrees;
            if smallModel, nTrees = max(60, round(cfg.RFTrees/2)); end
            mdl = TreeBagger(nTrees, Phi, y, ...
                'Method','classification', ...
                'MinLeafSize', cfg.RFMinLeaf, ...
                'OOBPrediction','off');
            model = struct();
            model.type = 'treebagger';
            model.mdl = mdl;
            return;
        catch ME
            warning('DAREMO:TreeBaggerFallback', 'TreeBagger failed, using kNN fallback: %s', ME.message);
        end
    end

    % Pure MATLAB fallback: weighted kNN on pair features.
    if size(Phi,1) > cfg.KNNMaxTrain
        idx = randperm(size(Phi,1), cfg.KNNMaxTrain);
        Phi = Phi(idx,:);
        y = y(idx);
    end
    model = struct();
    model.type = 'knn';
    model.X = Phi;
    model.y = y(:);
    model.K = min(cfg.KNNK, numel(y));
end

%% ------------------------------------------------------------------------
function pred = DA_PredictClass(model, Phi)
    P = DA_PredictProba3(model,Phi);
    [~,idx] = max(P,[],2);
    pred = idx - 1;
end

%% ------------------------------------------------------------------------
function P = DA_PredictProba3(model, Phi)
    if isempty(Phi)
        P = zeros(0,3); return;
    end
    switch lower(model.type)
        case 'treebagger'
            [~,score] = predict(model.mdl, Phi);
            P = zeros(size(Phi,1),3);
            cls = model.mdl.ClassNames;
            for k = 1:numel(cls)
                if iscell(cls)
                    c = str2double(cls{k});
                else
                    c = double(cls(k));
                end
                if ~isnan(c) && c >= 0 && c <= 2
                    P(:,round(c)+1) = score(:,k);
                end
            end
            s = sum(P,2);
            bad = s <= 0;
            P(~bad,:) = P(~bad,:) ./ s(~bad);
            P(bad,:) = 1/3;

        otherwise
            P = DA_KNNProba(model, Phi);
    end
end

%% ------------------------------------------------------------------------
function P = DA_KNNProba(model, Phi)
    n = size(Phi,1);
    P = zeros(n,3);
    chunk = 1024;
    for st = 1:chunk:n
        ed = min(n, st+chunk-1);
        Dist = DA_SquaredDistance(Phi(st:ed,:), model.X);
        [sd, ord] = sort(Dist,2,'ascend');
        K = min(model.K, size(ord,2));
        ord = ord(:,1:K);
        sd = sd(:,1:K);
        w = 1 ./ (sqrt(sd) + 1e-12);
        for r = 1:size(ord,1)
            labels = model.y(ord(r,:));
            for cls = 0:2
                P(st+r-1,cls+1) = sum(w(r,labels==cls));
            end
        end
    end
    s = sum(P,2);
    bad = s <= 0;
    P(~bad,:) = P(~bad,:) ./ s(~bad);
    P(bad,:) = 1/3;
end

%% ------------------------------------------------------------------------
function acc = DA_BalancedAccuracy(yTrue, yPred)
    classes = unique(yTrue(:))';
    rec = zeros(1,numel(classes));
    for i = 1:numel(classes)
        c = classes(i);
        mask = yTrue == c;
        if sum(mask) == 0
            rec(i) = 0;
        else
            rec(i) = mean(yPred(mask) == c);
        end
    end
    acc = mean(rec);
end

%% ------------------------------------------------------------------------
function [tr, va] = DA_TrainValSplit(y, valFrac)
    y = y(:);
    n = numel(y);
    val = false(n,1);
    classes = unique(y)';
    for c = classes
        idx = find(y==c);
        idx = idx(randperm(numel(idx)));
        nv = max(1, round(valFrac*numel(idx)));
        if numel(idx) - nv < 1
            nv = max(0,numel(idx)-1);
        end
        if nv > 0
            val(idx(1:nv)) = true;
        end
    end
    if sum(val) == 0
        idx = randperm(n,max(1,round(valFrac*n)));
        val(idx) = true;
    end
    if sum(~val) == 0
        val(randperm(n,1)) = false;
    end
    va = find(val);
    tr = find(~val);
end

%% ------------------------------------------------------------------------
function [Fn, zmin, span] = DA_NormalizeObjectives(F)
    zmin = min(F,[],1);
    zmax = max(F,[],1);
    span = max(zmax-zmin, 1e-12);
    Fn = (F - repmat(zmin,size(F,1),1)) ./ repmat(span,size(F,1),1);
end

%% ------------------------------------------------------------------------
function s = DA_RobustRelativeSpan(v)
    v = v(:);
    q = prctile(v,[5 25 50 75 95]);
    iqrV = max(q(4)-q(2),1e-12);
    span = max(q(5)-q(1),1e-12);
    s = log1p(span/(abs(q(3))+iqrV+1e-12));
end

%% ------------------------------------------------------------------------
function nd = DA_ParetoFrontMask(F)
    N = size(F,1);
    nd = true(N,1);
    for i = 1:N
        if ~nd(i), continue; end
        dominatedByAny = all(F <= repmat(F(i,:),N,1)+1e-12,2) & any(F < repmat(F(i,:),N,1)-1e-12,2);
        if any(dominatedByAny)
            nd(i) = false;
        end
    end
end

%% ------------------------------------------------------------------------
function tf = DA_Dominates(a,b)
    tf = all(a <= b + 1e-12) && any(a < b - 1e-12);
end

%% ------------------------------------------------------------------------
function label = DA_PBIRelationLabel(fa, fb, W, theta, margin)
    if DA_Dominates(fa,fb)
        label = 0;
        return;
    end
    if DA_Dominates(fb,fa)
        label = 1;
        return;
    end
    q = DA_PBIQuality([fa;fb], W, theta);
    diff = q(1) - q(2);
    if diff < -margin
        label = 0;
    elseif diff > margin
        label = 1;
    else
        label = 2;
    end
end

%% ------------------------------------------------------------------------
function q = DA_PBIQuality(Y, W, theta)
    Wn = W ./ repmat(max(sqrt(sum(W.^2,2)),1e-12),1,size(W,2));
    proj = Y * Wn';
    closest = max(proj,0);
    N = size(Y,1);
    R = size(Wn,1);
    pbi = zeros(N,R);
    for r = 1:R
        V = Y - closest(:,r) * Wn(r,:);
        d2 = sqrt(sum(V.^2,2));
        pbi(:,r) = closest(:,r) + theta*d2;
    end
    q = min(pbi,[],2);
end

%% ------------------------------------------------------------------------
function W = DA_RandomReferenceVectors(M, nVectors)
    if M <= 0, error('Number of objectives must be positive.'); end
    axes = eye(M);
    center = ones(1,M)/M;
    remaining = max(0, nVectors - size(axes,1) - 1);
    if remaining > 0
        E = -log(max(rand(remaining,M), realmin));
        E = E ./ repmat(sum(E,2),1,M);
        W = [axes; center; E];
    else
        W = [axes; center];
    end
    W = W(1:min(nVectors,size(W,1)),:);
    W = W ./ repmat(max(sqrt(sum(W.^2,2)),1e-12),1,M);
end

%% ------------------------------------------------------------------------
function Phi = DA_PairFeatures(Xa,Xb)
    Phi = [Xa-Xb, abs(Xa-Xb)];
end

%% ------------------------------------------------------------------------
function D2 = DA_SquaredDistance(A,B)
    aa = sum(A.^2,2);
    bb = sum(B.^2,2)';
    D2 = bsxfun(@plus, aa, bb) - 2*(A*B');
    D2(D2 < 0) = 0;
end

%% ------------------------------------------------------------------------
function X = DA_LHS(N,D,lower,upper)
%DA_LHS Simple Latin hypercube sampler. Not used by DAREMO_Infill directly,
%but useful for quick standalone tests.
    X = zeros(N,D);
    for j = 1:D
        perm = randperm(N)';
        X(:,j) = (perm - rand(N,1))/N;
    end
    X = repmat(lower,N,1) + X.*repmat(upper-lower,N,1);
end
