function demo_Convergence_10obj()
%DEMO_CONVERGENCE_10OBJ Convergence curves for the 10-objective, D=30 suite.
%   Compares REMO with the pruned Weighted AdaMaO variant on all sixteen
%   problems using the IGD traces already stored in every result file.
%   Nothing is re-run: the script only reads metric.IGD and result(:,1).
%
%   Run with:  demo_Convergence_10obj

%% 1. What to plot ------------------------------------------------------
dataRoot = 'C:\Users\lsx\Desktop\REMOandDREMO测试集\10目标\n30';
algorithms = { ...
    'REMO', ...
    'REMO_new2_AdaMaO_SDEOnly_UniformMix_Pruned_Weighted'};
labels = {'REMO','REMO-AdaMaO-W (pruned, weighted)'};
gridLabels = {'REMO','AdaMaO-W'};   % short version for the 4x4 overview

problems = {'DTLZ1','DTLZ2','DTLZ3','DTLZ4', ...
            'DTLZ5','DTLZ6','DTLZ7', ...
            'WFG1','WFG2','WFG3','WFG4', ...
            'WFG5','WFG6','WFG7','WFG8','WFG9'};

metric = 'IGD';
M      = 10;
maxFE  = 300;
runs   = 1:30;
colors = [0.12 0.42 0.72;    % REMO     - blue
          0.85 0.22 0.18];   % AdaMaO-W - red

%% 2. Environment -------------------------------------------------------
here        = fileparts(mfilename('fullpath'));
platemoRoot = fileparts(here);
addpath(genpath(fullfile(platemoRoot,'PlatEMO')));
addpath(here);
fprintf('PlatEMO added to path: %s\n',platemoRoot);

outputDir = fullfile(dataRoot,'ConvergenceCurves');
if ~isfolder(outputDir), mkdir(outputDir); end
fprintf('Output folder: %s\n\n',outputDir);

%% 3. Draw --------------------------------------------------------------
res = PlotConvergenceGrid( ...
    'problems',   problems, ...
    'dataRoot',   dataRoot, ...
    'algorithms', algorithms, ...
    'labels',     labels, ...
    'gridLabels', gridLabels, ...
    'metric',     metric, ...
    'M',          M, ...
    'runs',       runs, ...
    'maxFE',      maxFE, ...
    'colors',     colors, ...
    'logY',       true, ...
    'outputDir',  outputDir, ...
    'fileTag',    'convergence_IGD_10obj', ...
    'formats',    {'png'}, ...
    'gridShape',  [4 4], ...
    'quiet',      true);

%% 4. Final-value comparison table --------------------------------------
%  'at FE=300' is the right edge of the plotted curves. 'last snapshot' is the
%  median of each run's own final stored value, which is the number a paper
%  table usually quotes.
fprintf('\n===== final median %s (M=%d, D=30, %d runs) =====\n', ...
    metric,M,numel(runs));
fprintf('%-7s %13s %13s %13s %13s  %s\n','prob', ...
    [labels{1} ' @300'],[labels{2} ' @300'], ...
    [labels{1} ' last'],[labels{2} ' last'],'lower wins');
nWin = zeros(1,numel(algorithms));
for i = 1 : numel(problems)
    if isempty(res.results{i}), continue; end
    atEdge = cellfun(@(s)s.finalMedian,res.results{i}.curves);
    last   = cellfun(@(s)s.finalSnapshotMedian,res.results{i}.curves);
    [~,best] = min(last);
    nWin(best) = nWin(best) + 1;
    fprintf('%-7s %13.4g %13.4g %13.4g %13.4g  %s\n', ...
        problems{i},atEdge(1),atEdge(2),last(1),last(2),labels{best});
end
fprintf('%-7s %13d %13d\n','wins (by last snapshot)',nWin(1),nWin(2));
fprintf('\nDone. Figures are in %s\n',outputDir);
end
