function ComputeIGDp_M10_AllAlgs(workers)
%ComputeIGDp_M10_AllAlgs IGD+ of every stored run, seven algorithms at M=10.
%   Read-only with respect to the dataset. IGD+ is evaluated with the
%   official metric on the same optimum set that produced the stored IGD, so
%   all algorithms of one problem share exactly the same reference set and the
%   values are directly comparable. Every snapshot of every run is computed,
%   because the stored traces carry a different number of snapshots from one
%   algorithm to another.
%   Results are grouped by algorithm: one folder per algorithm, one .mat per
%   problem inside it, plus two summary tables at the top level. Existing
%   result files are skipped, so the runner is restartable.

    if nargin < 1, workers = 5; end
    platform = 'D:\PlatEMO-master\PlatEMO-master\PlatEMO';
    root     = 'C:\Users\lsx\Desktop\REMOandDREMO测试集\10目标\n30';
    outRoot  = 'C:\Users\lsx\Desktop\AdaMao实验表\IGDplus_M10';
    % Ours first, then the six baselines of the paper, in figure order.
    algs = {'REMO_UniformMix_Pruned_Weighted_Lambdat030', ...
            'REMO','PIEA','CSEA','PCSAEA_N100','KRVEA_100','MCEAD'};
    problems = {'DTLZ1','DTLZ2','DTLZ3','DTLZ4','DTLZ5','DTLZ6','DTLZ7', ...
                'WFG1','WFG2','WFG3','WFG4','WFG5','WFG6','WFG7','WFG8','WFG9'};

    addpath(genpath(platform));
    igdpFile = which('IGDp');
    assert(~isempty(igdpFile) && strcmpi(fileparts(igdpFile), fullfile(platform,'Metrics')), ...
        'IGDp resolves to %s instead of the PlatEMO metric.', igdpFile);
    fprintf('IGD+ metric: %s\n', igdpFile);
    assert(isfolder(root), 'Missing dataset root: %s', root);
    if ~isfolder(outRoot), mkdir(outRoot); end

    pool = gcp('nocreate');
    if isempty(pool), pool = parpool('Processes', workers); end
    fprintf('Using %d process workers.\n', pool.NumWorkers);
    setup = parfevalOnAll(pool, @() addpath(genpath(platform)), 0);
    fetchOutputs(setup);

    finalRows = {}; statRows = {}; nFile = 0; tAll = tic;
    for a = 1:numel(algs)
        alg = algs{a};
        srcDir = fullfile(root, alg);
        assert(isfolder(srcDir), 'Missing algorithm folder: %s', srcDir);
        outDir = fullfile(outRoot, alg);
        if ~isfolder(outDir), mkdir(outDir); end
        for p = 1:numel(problems)
            prob = problems{p};
            d = dir(fullfile(srcDir, sprintf('%s_%s_M10_D*_*.mat', alg, prob)));
            if isempty(d)
                fprintf('[%s/%s] no result file, skipped.\n', alg, prob);
                continue;
            end
            files = cell(numel(d), 1); runIds = zeros(numel(d), 1); Ds = zeros(numel(d), 1);
            for i = 1:numel(d)
                tok = regexp(d(i).name, '_M10_D(\d+)_(\d+)\.mat$', 'tokens', 'once');
                assert(~isempty(tok), 'Unexpected file name: %s', d(i).name);
                files{i} = fullfile(srcDir, d(i).name);
                Ds(i) = str2double(tok{1});
                runIds(i) = str2double(tok{2});
            end
            [runIds, order] = sort(runIds); files = files(order); Ds = Ds(order);
            assert(numel(unique(Ds)) == 1, 'Inconsistent D for %s/%s.', alg, prob);

            outFile = fullfile(outDir, sprintf('%s_IGDp_M10.mat', prob));
            if isfile(outFile)
                fprintf('[%2d/%2d] %-45s %-6s already present, skipped.\n', a, numel(algs), alg, prob);
                continue;
            end
            tProb = tic;
            % One problem object per problem; every algorithm of this problem
            % shares the same reference set, which is what makes IGD+ comparable.
            pro = feval(prob, 'M', 10, 'D', Ds(1), 'N', 100, 'maxFE', 300);
            opt = pro.optimum;

            nRuns = numel(files);
            IGDpCell = cell(nRuns, 1); FECell = cell(nRuns, 1);
            parfor i = 1:nRuns
                S = load(files{i});
                r = S.result; n = size(r, 1);
                gp = nan(1, n); fe = nan(1, n);
                for k = 1:n
                    gp(k) = IGDp(r{k,2}, opt);
                    fe(k) = r{k,1};
                end
                IGDpCell{i} = gp; FECell{i} = fe;
            end

            nSnap = cellfun(@numel, IGDpCell);
            IGDpFinal = cellfun(@(v) v(end), IGDpCell);
            meta = struct('algorithm', alg, 'problem', prob, 'M', 10, 'D', Ds(1), ...
                'N', 100, 'maxFE', 300, 'metric', 'IGDp', ...
                'referenceSet', 'problem.optimum, generated by the problem class', ...
                'nReferencePoints', size(opt, 1), ...
                'snapshotCounts', nSnap, 'source', srcDir, ...
                'created', char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')));
            save(outFile, 'IGDpCell', 'FECell', 'runIds', 'IGDpFinal', 'meta', '-v7');
            nFile = nFile + 1;
            fprintf('[%2d/%2d] %-45s %-6s %2d runs x %s snaps | %.1fs (%.2f s/run) | mean IGD+ (final) %.4g\n', ...
                a, numel(algs), alg, prob, nRuns, mat2str(unique(nSnap)'), ...
                toc(tProb), toc(tProb)/nRuns, mean(IGDpFinal));

            for i = 1:nRuns
                finalRows{end+1} = table({alg}, {prob}, runIds(i), nSnap(i), ...
                    IGDpFinal(i), 'VariableNames', ...
                    {'algorithm','problem','runId','nSnapshots','IGDp_final'}); %#ok<AGROW>
            end
            statRows{end+1} = table({alg}, {prob}, nRuns, mean(IGDpFinal), ...
                median(IGDpFinal), std(IGDpFinal), min(IGDpFinal), max(IGDpFinal), ...
                'VariableNames', {'algorithm','problem','nRuns','mean','median', ...
                'std','min','max'}); %#ok<AGROW>
        end
    end

    if ~isempty(finalRows)
        writetable(vertcat(finalRows{:}), fullfile(outRoot, 'summary_final_IGDp_M10.csv'), 'Encoding', 'UTF-8');
    end
    if ~isempty(statRows)
        writetable(vertcat(statRows{:}), fullfile(outRoot, 'summary_stats_IGDp_M10.csv'), 'Encoding', 'UTF-8');
    end
    fprintf('\nCOMPLETE: %d problem file(s) written in %.1f min.\n', nFile, toc(tAll)/60);
    fprintf('Output: %s\n', outRoot);
end
