function ComputeIGDp_MultiM_AllAlgs(Mlist, workers)
%ComputeIGDp_MultiM_AllAlgs IGD+ of every stored run at M=15 and M=20.
%   Same construction as the M=10 pass: read-only with respect to the dataset,
%   the official IGD+ metric on the optimum set of the problem class, so every
%   algorithm of one problem shares exactly one reference set. Files whose
%   objective count does not match the requested M are ignored, because the
%   folder of REMO and PIEA at M=20 also holds leftover M=10 WFG4 runs.
%   Results are grouped per objective count and per algorithm.

    if nargin < 2 || isempty(workers), workers = 5; end
    if nargin < 1 || isempty(Mlist), Mlist = [15 20]; end
    platform = 'D:\PlatEMO-master\PlatEMO-master\PlatEMO';
    root     = 'C:\Users\lsx\Desktop\REMOandDREMO测试集';
    outBase  = 'C:\Users\lsx\Desktop\AdaMao实验表';
    algs = {'REMO_UniformMix_Pruned_Weighted_Lambdat030', ...
            'REMO','PIEA','CSEA','PCSAEA_N100','KRVEA_100','MCEAD'};
    problems = {'DTLZ1','DTLZ2','DTLZ3','DTLZ4','DTLZ5','DTLZ6','DTLZ7', ...
                'WFG1','WFG2','WFG3','WFG4','WFG5','WFG6','WFG7','WFG8','WFG9'};

    addpath(genpath(platform));
    igdpFile = which('IGDp');
    assert(~isempty(igdpFile) && strcmpi(fileparts(igdpFile), fullfile(platform,'Metrics')), ...
        'IGDp resolves to %s instead of the PlatEMO metric.', igdpFile);

    pool = gcp('nocreate');
    if isempty(pool), pool = parpool('Processes', workers); end
    fprintf('Using %d process workers.\n', pool.NumWorkers);
    setup = parfevalOnAll(pool, @() addpath(genpath(platform)), 0);
    fetchOutputs(setup);

    for mi = 1:numel(Mlist)
        M = Mlist(mi);
        srcRoot = fullfile(root, sprintf('%d目标', M));
        outRoot = fullfile(outBase, sprintf('IGDplus_M%d', M));
        assert(isfolder(srcRoot), 'Missing dataset root: %s', srcRoot);
        if ~isfolder(outRoot), mkdir(outRoot); end
        fprintf('\n===== M = %d\n', M);
        finalRows = {}; statRows = {}; nFile = 0; nSkipOtherM = 0; tM = tic;
        for a = 1:numel(algs)
            alg = algs{a};
            srcDir = fullfile(srcRoot, alg);
            assert(isfolder(srcDir), 'Missing algorithm folder: %s', srcDir);
            outDir = fullfile(outRoot, alg);
            if ~isfolder(outDir), mkdir(outDir); end
            for p = 1:numel(problems)
                prob = problems{p};
                dAll = dir(fullfile(srcDir, sprintf('%s_%s_M*_D*_*.mat', alg, prob)));
                files = {}; runIds = []; Ds = [];
                for i = 1:numel(dAll)
                    tok = regexp(dAll(i).name, '_M(\d+)_D(\d+)_(\d+)\.mat$', 'tokens', 'once');
                    if isempty(tok), continue; end
                    if str2double(tok{1}) ~= M, nSkipOtherM = nSkipOtherM + 1; continue; end
                    files{end+1} = fullfile(srcDir, dAll(i).name); %#ok<AGROW>
                    Ds(end+1)    = str2double(tok{2}); %#ok<AGROW>
                    runIds(end+1) = str2double(tok{3}); %#ok<AGROW>
                end
                if isempty(files)
                    fprintf('[%s/M%d] no result file, skipped.\n', alg, M);
                    continue;
                end
                runIds = runIds(:); Ds = Ds(:);
                [runIds, order] = sort(runIds); files = files(order); Ds = Ds(order);
                assert(numel(unique(Ds)) == 1, 'Inconsistent D for %s/%s.', alg, prob);

                outFile = fullfile(outDir, sprintf('%s_IGDp_M%d.mat', prob, M));
                if isfile(outFile)
                    fprintf('[%d/7] %-45s %-6s already present, skipped.\n', a, alg, prob);
                    continue;
                end
                tProb = tic;
                pro = feval(prob, 'M', M, 'D', Ds(1), 'N', 100, 'maxFE', 300);
                opt = pro.optimum;

                nRuns = numel(files);
                IGDpCell = cell(nRuns, 1); FECell = cell(nRuns, 1);
                parfor i = 1:nRuns
                    S = load(files{i});
                    r = S.result; n = size(r, 1);
                    gp = nan(1, n); fe = nan(1, n);
                    for k = 1:n
                        gp(k) = IGDp(r{k,2}, opt);
                        fe(k) = r{k,1};
                    end
                    IGDpCell{i} = gp; FECell{i} = fe;
                end
                nSnap = cellfun(@numel, IGDpCell);
                IGDpFinal = cellfun(@(v) v(end), IGDpCell);
                feEnd = cellfun(@(v) v(end), FECell);
                meta = struct('algorithm', alg, 'problem', prob, 'M', M, 'D', Ds(1), ...
                    'N', 100, 'maxFE', 300, 'metric', 'IGDp', ...
                    'referenceSet', 'problem.optimum, generated by the problem class', ...
                    'nReferencePoints', size(opt, 1), 'snapshotCounts', nSnap, ...
                    'finalFE', feEnd, 'source', srcDir, ...
                    'created', char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')));
                save(outFile, 'IGDpCell', 'FECell', 'runIds', 'IGDpFinal', 'meta', '-v7');
                nFile = nFile + 1;
                fprintf('[%d/7] %-45s %-6s %2d runs x %s snaps | FEend %g..%g | %.1fs | mean IGD+ %.4g\n', ...
                    a, alg, prob, nRuns, mat2str(unique(nSnap)'), min(feEnd), max(feEnd), ...
                    toc(tProb), mean(IGDpFinal));

                for i = 1:nRuns
                    finalRows{end+1} = table({alg}, {prob}, runIds(i), nSnap(i), ...
                        feEnd(i), IGDpFinal(i), 'VariableNames', ...
                        {'algorithm','problem','runId','nSnapshots','finalFE','IGDp_final'}); %#ok<AGROW>
                end
                statRows{end+1} = table({alg}, {prob}, nRuns, mean(IGDpFinal), ...
                    median(IGDpFinal), std(IGDpFinal), min(IGDpFinal), max(IGDpFinal), ...
                    'VariableNames', {'algorithm','problem','nRuns','mean','median', ...
                    'std','min','max'}); %#ok<AGROW>
            end
        end
        if ~isempty(finalRows)
            writetable(vertcat(finalRows{:}), fullfile(outRoot, sprintf('summary_final_IGDp_M%d.csv', M)), 'Encoding', 'UTF-8');
        end
        if ~isempty(statRows)
            writetable(vertcat(statRows{:}), fullfile(outRoot, sprintf('summary_stats_IGDp_M%d.csv', M)), 'Encoding', 'UTF-8');
        end
        fprintf('M=%d: %d file(s) written in %.1f min (ignored %d file(s) of another M).\n', ...
            M, nFile, toc(tM)/60, nSkipOtherM);
    end
    fprintf('\nALL DONE\n');
end
