function ComputeDTLZ7Serial(alg, M, maxRuns)
%ComputeDTLZ7Serial Compute DTLZ7 IGD+ strictly serially, one snapshot at a time,
%   with a progress line per evaluation. The parallel passes died here without
%   leaving an exception, so this version is meant to (a) confirm that a plain
%   serial loop survives the whole problem, and (b) pinpoint the exact snapshot
%   if it does not.

    if nargin < 1 || isempty(alg)
        alg = 'REMO_UniformMix_Pruned_Weighted_Lambdat030_NoBatchDist';
    end
    if nargin < 2 || isempty(M), M = 20; end
    if nargin < 3 || isempty(maxRuns), maxRuns = inf; end

    addpath(genpath('D:\PlatEMO-master\PlatEMO-master\PlatEMO'));
    rawRoot = 'C:\Users\lsx\Desktop\REMOandDREMO测试集';
    outBase = 'C:\Users\lsx\Desktop\AdaMao实验表';
    rawDir  = fullfile(rawRoot, sprintf('%d目标', M), alg);
    outDir  = fullfile(outBase, sprintf('IGDplus_M%d', M), alg);
    if ~isfolder(outDir), mkdir(outDir); end

    d = dir(fullfile(rawDir, sprintf('%s_DTLZ7_M%d_D*_*.mat', alg, M)));
    assert(~isempty(d), 'No DTLZ7 file in %s', rawDir);
    files = cell(numel(d), 1); runIds = zeros(numel(d), 1); Ds = zeros(numel(d), 1);
    for i = 1:numel(d)
        tok = regexp(d(i).name, sprintf('_M%d_D(\\d+)_(\\d+)\\.mat$', M), 'tokens', 'once');
        files{i} = fullfile(rawDir, d(i).name);
        Ds(i) = str2double(tok{1}); runIds(i) = str2double(tok{2});
    end
    [runIds, ord] = sort(runIds); files = files(ord); Ds = Ds(ord);
    D = Ds(1);

    fprintf('DTLZ7 serial pass: %d files, D=%d, maxRuns=%g\n', numel(files), D, maxRuns);
    t0 = tic;
    pro = feval('DTLZ7', 'M', M, 'D', D, 'N', 100, 'maxFE', 300);
    opt = pro.optimum;
    fprintf('reference set: %d points (%.1f MB), built in %.1f s\n', ...
        size(opt,1), numel(opt)*8/1e6, toc(t0));

    IGDpCell = cell(numel(files), 1); FECell = cell(numel(files), 1);
    nDone = 0;
    for i = 1:numel(files)
        S = load(files{i});
        r = S.result; n = size(r, 1);
        gp = nan(1, n); fe = nan(1, n);
        for k = 1:n
            t = tic;
            gp(k) = IGDpFast(r{k,2}, opt);
            fe(k) = r{k,1};
            fprintf('  run %02d snap %02d/%02d  FE=%3g  IGDp=%.8g  (%.2f s, total %.1f min)\n', ...
                runIds(i), k, n, fe(k), gp(k), toc(t), toc(t0)/60);
        end
        IGDpCell{i} = gp; FECell{i} = fe;
        nDone = nDone + 1;
        if nDone >= maxRuns
            fprintf('\nstopped after %d run(s)\n', nDone);
            return;
        end
    end

    IGDpFinal = cellfun(@(v) v(end), IGDpCell);
    meta = struct('algorithm', alg, 'problem', 'DTLZ7', 'M', M, 'D', D, ...
        'N', 100, 'maxFE', 300, 'metric', 'IGDp', ...
        'referenceSet', 'problem.optimum, generated by the problem class', ...
        'nReferencePoints', size(opt,1), 'snapshotCounts', cellfun(@numel, IGDpCell), ...
        'source', rawDir, 'created', char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')));
    prodFile = fullfile(outDir, sprintf('DTLZ7_IGDp_M%d.mat', M));
    save(prodFile, 'IGDpCell', 'FECell', 'runIds', 'IGDpFinal', 'meta', '-v7');

    for i = 1:numel(files)
        want = IGDpCell{i}(:);
        Sm = load(files{i}, 'metric');
        if isfield(Sm.metric, 'IGDp') && isequal(Sm.metric.IGDp(:), want), continue; end
        metric = Sm.metric; %#ok<NASGU>
        metric.IGDp = want;
        save(files{i}, 'metric', '-append');
        V = load(files{i}, 'metric');
        assert(isequal(V.metric.IGDp(:), want), 'verify failed: %s', files{i});
    end
    fprintf('\nDTLZ7 DONE: %.1f min, mean IGD+ %.6g\n', toc(t0)/60, mean(IGDpFinal));
end
