function PlotConvergencePaperStyle()
%PLOTCONVERGENCEPAPERSTYLE Paper-style convergence figure (method A, no re-run).
%   The layout used by most EMTO papers: a linear IGD axis, sparse marker
%   lines, Times New Roman, legend in the lower-left corner and no IQR band.
%   Reads the stored traces of six baselines and PACDIS on 10-objective WFG7,
%   matched runs 1-20 (baselines store 30 runs, PACDIS 20).
%
%   The two knobs that produce this look:
%     'gridStep',20   -> only every 20th FE becomes a vertex, so the curve is a
%                        readable polyline instead of a dense staircase
%     'markers',{...} -> one symbol per algorithm
%
%   Run with: PlotConvergencePaperStyle

    platemoRoot = 'D:\PlatEMO-master\PlatEMO-master';
    addpath(genpath(fullfile(platemoRoot,'PlatEMO')));
    addpath(fullfile(platemoRoot,'ConvergencePlot'));

    dataRoot = 'C:\Users\lsx\Desktop\REMOandDREMO测试集\10目标\n30';
    outDir   = fullfile(platemoRoot,'ConvergencePlot','output');
    if ~isfolder(outDir), mkdir(outDir); end

    algorithms = {'REMO','PIEA','CSEA','PCSAEA_N100','KRVEA_100','MCEAD', ...
                  'REMO_UniformMix_Pruned_Weighted_Lambdat030'};
    labels = {'REMO','PIEA','CSEA','PC-SAEA','K-RVEA','MCEA/D','PACDIS (ours)'};
    markers = {'^','o','*','s','x','+','D'};
    colors = [0.16 0.35 0.60; ...
              0.90 0.60 0.10; ...
              0.20 0.55 0.30; ...
              0.50 0.30 0.65; ...
              0.35 0.70 0.85; ...
              0.45 0.45 0.45; ...
              0.85 0.12 0.12];
    filled = [false false false false false false true];   % only ours is solid

    PlotConvergenceCurves('WFG7', ...
        'dataRoot',       dataRoot, ...
        'algorithms',     algorithms, ...
        'labels',         labels, ...
        'colors',         colors, ...
        'markers',        markers, ...
        'markerSize',     6, ...
        'markerFilled',   filled, ...
        'showBand',       false, ...
        'logY',           false, ...
        'fontName',       'Times New Roman', ...
        'legendLocation', 'southwest', ...
        'yLabel',         'IGD values', ...
        'metric',         'IGD', ...
        'M',              10, ...
        'runs',           1:20, ...
        'maxFE',          300, ...
        'gridStep',       20, ...
        'titleMode',      'none', ...
        'showFinal',      false);

    fig = gcf;
    set(fig,'Color','w','Position',[80 60 780 560]);
    ax = gca;
    ax.Toolbar.Visible = 'off';
    xlim(ax,[95 305]);
    ylim(ax,[4.6 9.5]);        % keeps the legend clear of the PACDIS mid-section

    pngFile = fullfile(outDir,'convergence_paperstyle_WFG7_M10_7algs.png');
    pdfFile = fullfile(outDir,'convergence_paperstyle_WFG7_M10_7algs.pdf');
    exportgraphics(fig,pngFile,'Resolution',300);
    exportgraphics(fig,pdfFile,'ContentType','vector');
    fprintf('\nSaved:\n  %s\n  %s\n',pngFile,pdfFile);
end
