function PlotFE500M10Candidates()
%PLOTFE500M10CANDIDATES Candidate single-panel convergence figures, FE=500, M=10.
%   Six current baselines + PACDIS (NoBatchDist), paper style: linear metric
%   axis, sparse marker polyline, Times New Roman, no IQR band. Used to pick
%   the four panels of the final 2x2 grid.

    platemoRoot = 'D:\PlatEMO-master\PlatEMO-master';
    addpath(genpath(fullfile(platemoRoot,'PlatEMO')));
    addpath(fullfile(platemoRoot,'ConvergencePlot'));

    dataRoot = 'C:\Users\lsx\Desktop\REMOandDREMO测试集\10目标\n30\FE500';
    outDir   = fullfile(platemoRoot,'ConvergencePlot','output','fe500_m10_candidates');
    if ~isfolder(outDir), mkdir(outDir); end

    algorithms = {'REMO','PCSAEA','CSEA','HES_EA','SSDE','SAMOEATL2M', ...
                  'REMO_UniformMix_Pruned_Weighted_Lambdat030_NoBatchDist'};
    labels  = {'REMO','PC-SAEA','CSEA','HES-EA','SSDE','SAMOEA-TL2M','PACDIS (ours)'};
    markers = {'^','o','*','s','x','+','D'};
    colors  = [0.16 0.35 0.60; ...
               0.90 0.60 0.10; ...
               0.20 0.55 0.30; ...
               0.50 0.30 0.65; ...
               0.35 0.70 0.85; ...
               0.45 0.45 0.45; ...
               0.85 0.12 0.12];
    filled  = [false false false false false false true];

    probs  = {'DTLZ1','DTLZ2','DTLZ4','DTLZ6','WFG1','WFG2','WFG7','WFG8'};
    metric = 'IGDp';

    for ip = 1:numel(probs)
        p = probs{ip};
        f = figure('Color','w','Position',[80 60 900 560]);
        PlotConvergenceCurves(p, ...
            'dataRoot',       dataRoot, ...
            'algorithms',     algorithms, ...
            'labels',         labels, ...
            'colors',         colors, ...
            'markers',        markers, ...
            'markerSize',     6, ...
            'markerFilled',   filled, ...
            'showBand',       false, ...
            'logY',           false, ...
            'fontName',       'Times New Roman', ...
            'legendLocation', 'eastoutside', ...
            'yLabel',         [metric ' values'], ...
            'metric',         metric, ...
            'M',              10, ...
            'runs',           1:20, ...
            'maxFE',          500, ...
            'gridStep',       50, ...
            'titleMode',      'compact', ...
            'showFinal',      false, ...
            'verbose',        true);
        ax = gca;
        ax.Toolbar.Visible = 'off';
        xlim(ax,[0 500]);
        pngFile = fullfile(outDir,sprintf('cand_%s_M10_%s.png',p,metric));
        exportgraphics(f,pngFile,'Resolution',200);
        close(f);
        fprintf('saved %s\n',pngFile);
    end
    fprintf('\nALL DONE\n');
end
