function PlotFE500M10Grid()
%PLOTFE500M10GRID Final 2x2 convergence panel, FE=500, M=10, IGD+.
%   Six current baselines + PACDIS (NoBatchDist) on four representative
%   problems. Paper style copied from PlotConvergencePaperStyle.m: linear
%   metric axis, sparse marker polyline (gridStep 50), Times New Roman, no
%   IQR band, hollow markers except ours.
%
%   Run with: PlotFE500M10Grid

    platemoRoot = 'D:\PlatEMO-master\PlatEMO-master';
    addpath(genpath(fullfile(platemoRoot,'PlatEMO')));
    addpath(fullfile(platemoRoot,'ConvergencePlot'));

    dataRoot = 'C:\Users\lsx\Desktop\REMOandDREMO测试集\10目标\n30\FE500';
    outDir   = fullfile(platemoRoot,'ConvergencePlot','output');
    if ~isfolder(outDir), mkdir(outDir); end

    algorithms = {'REMO','PCSAEA','CSEA','HES_EA','SSDE','SAMOEATL2M', ...
                  'REMO_UniformMix_Pruned_Weighted_Lambdat030_NoBatchDist'};
    labels  = {'REMO','PC-SAEA','CSEA','HES-EA','SSDE','SAMOEA-TL2M','PACDIS (ours)'};
    markers = {'^','o','*','s','x','+','D'};
    colors  = [0.16 0.35 0.60; ...
               0.90 0.60 0.10; ...
               0.20 0.55 0.30; ...
               0.50 0.30 0.65; ...
               0.35 0.70 0.85; ...
               0.45 0.45 0.45; ...
               0.85 0.12 0.12];
    filled  = [false false false false false false true];

    probs  = {'DTLZ1','DTLZ6','WFG2','WFG7'};
    metric = 'IGDp';

    fig = figure('Color','w','Position',[60 60 1080 720]);
    tl  = tiledlayout(fig,2,2,'TileSpacing','compact','Padding','compact');
    axs = gobjects(1,numel(probs));

    for i = 1:numel(probs)
        ax = nexttile(tl);
        axs(i) = ax;
        PlotConvergenceCurves(probs{i}, ...
            'dataRoot',       dataRoot, ...
            'algorithms',     algorithms, ...
            'labels',         labels, ...
            'colors',         colors, ...
            'markers',        markers, ...
            'markerSize',     5, ...
            'markerFilled',   filled, ...
            'showBand',       false, ...
            'logY',           false, ...
            'fontName',       'Times New Roman', ...
            'legendLocation', 'none', ...
            'showAxisLabels', false, ...
            'metric',         metric, ...
            'M',              10, ...
            'runs',           1:20, ...
            'maxFE',          500, ...
            'gridStep',       50, ...
            'titleMode',      'none', ...
            'showFinal',      false, ...
            'verbose',        false, ...
            'axes',           ax);
        xlim(ax,[95 505]);
        ax.Toolbar.Visible = 'off';
        title(ax,sprintf('(%s) %s',char('a'+i-1),probs{i}), ...
            'FontName','Times New Roman','FontSize',11,'Interpreter','none');
    end

    xlabel(axs(3),'Number of function evaluations','FontName','Times New Roman','FontSize',10);
    xlabel(axs(4),'Number of function evaluations','FontName','Times New Roman','FontSize',10);
    ylabel(axs(1),[metric ' values'],'FontName','Times New Roman','FontSize',10);
    ylabel(axs(3),[metric ' values'],'FontName','Times New Roman','FontSize',10);

    % top row shares the x axis with the bottom row: drop the duplicated ticks
    axs(1).XTickLabel = [];
    axs(2).XTickLabel = [];

    % one shared legend at the bottom; remove the per-axes legends first
    delete(findall(fig,'Type','legend'));
    hAll = flipud(findobj(axs(1),'Type','line'));
    lgd  = legend(axs(1),hAll(1:numel(algorithms)),labels);
    set(lgd,'Orientation','horizontal','NumColumns',4,'Box','on', ...
        'FontName','Times New Roman','FontSize',9);
    lgd.Layout.Tile = 'south';

    pngFile = fullfile(outDir,sprintf('convergence_fe500_M10_%s_2x2.png',metric));
    pdfFile = fullfile(outDir,sprintf('convergence_fe500_M10_%s_2x2.pdf',metric));
    exportgraphics(fig,pngFile,'Resolution',300);
    exportgraphics(fig,pdfFile,'ContentType','vector');
    fprintf('\nSaved:\n  %s\n  %s\n',pngFile,pdfFile);
end
