function [candidateRows,generationRow,primaryEligible] = ...
    BuildCascadeAuditRows(run,generation,fe,progress,candidateMode, ...
    trace,shadow,counterfactual,cvKendall)
%BuildCascadeAuditRows - Build versioned candidate and generation audit rows.

    audit = CascadeAuditSchema();
    validateInputs(run,generation,fe,progress,candidateMode,trace, ...
        shadow,counterfactual,cvKendall,audit);

    candidateCount = numel(trace.RelationScore);
    candidateIndex = (1:candidateCount)';
    relationScore = trace.RelationScore(:);
    indicatorScore = trace.IndicatorScore(:);
    coarseKept = logical(trace.CoarseKept(:));
    selectedMask = logical(trace.SelectedMask(:));
    feasibleMask = logical(shadow.FeasibleMask(:));
    marginalIGDp = shadow.MarginalIGDp(:);
    replacementGain = counterfactual.ReplacementGain(:);
    operationalIndicatorUsed = logical(trace.OperationalIndicatorUsed);

    relationPercentile = RankPercentileDescending(relationScore);
    indicatorAvailable = all(isfinite(indicatorScore));
    if indicatorAvailable
        indicatorPercentile = RankPercentileDescending(indicatorScore);
        positiveDisagreement = indicatorPercentile-relationPercentile;
    else
        indicatorPercentile = NaN(candidateCount,1);
        positiveDisagreement = NaN(candidateCount,1);
    end

    tolerance = max(1e-12, ...
        1e-10*max(1,abs(shadow.BaselineIGDp)));
    useful = marginalIGDp > tolerance;
    batchSize = counterfactual.BatchSize;
    oracleTopK = topKMask(marginalIGDp,batchSize);
    if indicatorAvailable
        indicatorTopK = topKMask(indicatorScore,batchSize);
    else
        indicatorTopK = NaN(candidateCount,1);
    end

    nearestSelectedDistance = nearestSelectedDistances( ...
        trace.CandidateDecisions,trace.Lower,trace.Upper, ...
        coarseKept,selectedMask);
    [highDisagreement,maxDisagreement] = disagreementSets( ...
        positiveDisagreement,indicatorPercentile, ...
        relationPercentile,coarseKept);

    candidateRows = NaN(candidateCount, ...
        numel(audit.columns.candidateRows));
    candidateRows(:,column(audit,'candidateRows','Run')) = run;
    candidateRows(:,column(audit,'candidateRows','Generation')) = ...
        generation;
    candidateRows(:,column(audit,'candidateRows','FE')) = fe;
    candidateRows(:,column(audit,'candidateRows','PostInitProgress')) = ...
        progress;
    candidateRows(:,column(audit,'candidateRows','CandidateIndex')) = ...
        candidateIndex;
    candidateRows(:,column(audit,'candidateRows','CandidateMode')) = ...
        candidateMode;
    candidateRows(:,column(audit,'candidateRows', ...
        'OperationalIndicatorUsed')) = double(operationalIndicatorUsed);
    candidateRows(:,column(audit,'candidateRows','RelationScore')) = ...
        relationScore;
    candidateRows(:,column(audit,'candidateRows', ...
        'RelationPercentile')) = relationPercentile;
    candidateRows(:,column(audit,'candidateRows','IndicatorScore')) = ...
        indicatorScore;
    candidateRows(:,column(audit,'candidateRows', ...
        'IndicatorPercentile')) = indicatorPercentile;
    candidateRows(:,column(audit,'candidateRows', ...
        'PositiveDisagreement')) = positiveDisagreement;
    candidateRows(:,column(audit,'candidateRows','CoarseKept')) = ...
        double(coarseKept);
    candidateRows(:,column(audit,'candidateRows','BaselineSelected')) = ...
        double(selectedMask);
    candidateRows(:,column(audit,'candidateRows','ShadowFeasible')) = ...
        double(feasibleMask);
    candidateRows(:,column(audit,'candidateRows','MarginalIGDp')) = ...
        marginalIGDp;
    candidateRows(:,column(audit,'candidateRows','Useful')) = ...
        double(useful);
    candidateRows(:,column(audit,'candidateRows','ReplacementGain')) = ...
        replacementGain;
    candidateRows(:,column(audit,'candidateRows', ...
        'NearestSelectedDistance')) = nearestSelectedDistance;
    candidateRows(:,column(audit,'candidateRows','OracleTopK')) = ...
        double(oracleTopK);
    candidateRows(:,column(audit,'candidateRows','IndicatorTopK')) = ...
        double(indicatorTopK);
    candidateRows(:,column(audit,'candidateRows', ...
        'MaxPositiveDisagreement')) = double(maxDisagreement);

    usefulOracleCount = nnz(oracleTopK & useful);
    if usefulOracleCount > 0
        recallAtK = nnz(coarseKept & oracleTopK & useful)/ ...
            usefulOracleCount;
    else
        recallAtK = NaN;
    end
    usefulCount = nnz(useful);
    if usefulCount > 0
        usefulFNR = nnz(~coarseKept & useful)/usefulCount;
    else
        usefulFNR = NaN;
    end

    maximumUtility = max(marginalIGDp);
    if maximumUtility > tolerance
        maximumCoarseUtility = max(marginalIGDp(coarseKept));
        singleCoverageRegret = max(0, ...
            maximumUtility-maximumCoarseUtility);
    else
        singleCoverageRegret = NaN;
    end

    rejectedMask = ~coarseKept;
    rejectedGain = replacementGain(rejectedMask);
    rejectedGainKnown = ~isempty(rejectedGain) && ...
        all(isfinite(rejectedGain));
    replacementTolerance = max(1e-12,1e-10*max(1, ...
        abs(counterfactual.BaselineBatchIGDp)));
    if indicatorAvailable
        rescueCandidates = rejectedMask & indicatorTopK;
    else
        rescueCandidates = false(candidateCount,1);
    end
    if any(rescueCandidates) && ...
            all(isfinite(replacementGain(rescueCandidates)))
        rescueOpportunityRate = mean( ...
            replacementGain(rescueCandidates) > replacementTolerance);
    else
        rescueOpportunityRate = NaN;
    end
    if rejectedGainKnown
        rejectedPositiveRate = mean( ...
            rejectedGain > replacementTolerance);
    else
        rejectedPositiveRate = NaN;
    end
    if rejectedGainKnown && rejectedPositiveRate > 0 && ...
            any(highDisagreement)
        disagreementEnrichment = ...
            mean(replacementGain(highDisagreement) > ...
            replacementTolerance)/rejectedPositiveRate;
    else
        disagreementEnrichment = NaN;
    end

    maxDisagreementIndex = find(maxDisagreement,1);
    if ~isempty(maxDisagreementIndex) && ...
            isfinite(replacementGain(maxDisagreementIndex))
        maxDisagreementGain = replacementGain(maxDisagreementIndex);
        maxDisagreementSuccess = double( ...
            maxDisagreementGain > replacementTolerance);
    else
        maxDisagreementGain = NaN;
        maxDisagreementSuccess = NaN;
    end

    oracleRejectedGain = counterfactual.OracleRejectedReplacementGain;
    if counterfactual.HasReplacementOpportunity && ...
            oracleRejectedGain > 0
        if isfinite(maxDisagreementGain)
            capturedGain = max(maxDisagreementGain,0);
        else
            capturedGain = 0;
        end
        replacementCapture = capturedGain/oracleRejectedGain;
    else
        replacementCapture = 0;
    end

    if indicatorAvailable
        indicatorTopKMeanUtility = mean(marginalIGDp(indicatorTopK));
    else
        indicatorTopKMeanUtility = NaN;
    end

    generationRow = NaN(1,numel(audit.columns.generationRows));
    generationRow(column(audit,'generationRows','Run')) = run;
    generationRow(column(audit,'generationRows','Generation')) = ...
        generation;
    generationRow(column(audit,'generationRows','FE')) = fe;
    generationRow(column(audit,'generationRows','PostInitProgress')) = ...
        progress;
    generationRow(column(audit,'generationRows','CandidateMode')) = ...
        candidateMode;
    generationRow(column(audit,'generationRows', ...
        'OperationalIndicatorUsed')) = double(operationalIndicatorUsed);
    generationRow(column(audit,'generationRows','CandidateCount')) = ...
        candidateCount;
    generationRow(column(audit,'generationRows','CoarseCount')) = ...
        nnz(coarseKept);
    generationRow(column(audit,'generationRows','BatchSize')) = batchSize;
    generationRow(column(audit,'generationRows','ReferenceCount')) = ...
        shadow.ReferenceCount;
    generationRow(column(audit,'generationRows', ...
        'ShadowEvaluationCount')) = shadow.ShadowEvaluationCount;
    generationRow(column(audit,'generationRows','BaselineIGDp')) = ...
        shadow.BaselineIGDp;
    generationRow(column(audit,'generationRows','RecallAtK')) = recallAtK;
    generationRow(column(audit,'generationRows','UsefulFNR')) = usefulFNR;
    generationRow(column(audit,'generationRows', ...
        'SingleCoverageRegret')) = singleCoverageRegret;
    generationRow(column(audit,'generationRows', ...
        'NormalizedBatchCoverageRegret')) = ...
        counterfactual.NormalizedBatchCoverageRegret;
    generationRow(column(audit,'generationRows', ...
        'RescueOpportunityRate')) = rescueOpportunityRate;
    generationRow(column(audit,'generationRows', ...
        'DisagreementEnrichment')) = disagreementEnrichment;
    generationRow(column(audit,'generationRows','CVKendall')) = cvKendall;
    generationRow(column(audit,'generationRows', ...
        'MaxDisagreementReplacementGain')) = maxDisagreementGain;
    generationRow(column(audit,'generationRows', ...
        'MaxDisagreementSuccess')) = maxDisagreementSuccess;
    generationRow(column(audit,'generationRows', ...
        'OracleRejectedReplacementGain')) = oracleRejectedGain;
    generationRow(column(audit,'generationRows','ReplacementCapture')) = ...
        replacementCapture;
    generationRow(column(audit,'generationRows', ...
        'BaselineBatchUtility')) = counterfactual.BaselineBatchUtility;
    generationRow(column(audit,'generationRows', ...
        'IndicatorTopKMeanUtility')) = indicatorTopKMeanUtility;
    generationRow(column(audit,'generationRows', ...
        'FullReferenceRankCorrelation')) = NaN;
    generationRow(column(audit,'generationRows', ...
        'FullReferenceTopKOverlap')) = NaN;
    generationRow(column(audit,'generationRows','AuditSeconds')) = NaN;

    primaryEligible = candidateMode == ...
        audit.codes.candidateMode.indicator && operationalIndicatorUsed;
end

function mask = topKMask(values,k)
    count = numel(values);
    keys = [-values(:),(1:count)'];
    [~,order] = sortrows(keys,[1 2]);
    mask = false(count,1);
    mask(order(1:k)) = true;
end

function distance = nearestSelectedDistances( ...
    decisions,lower,upper,coarseKept,selectedMask)
    lower = reshape(lower,1,[]);
    upper = reshape(upper,1,[]);
    scaled = (decisions-lower)./(upper-lower);
    scaled = min(max(scaled,0),1);
    selected = scaled(selectedMask,:);
    dimension = size(scaled,2);
    distance = NaN(size(scaled,1),1);
    rejectedIndex = find(~coarseKept);
    for i = 1:numel(rejectedIndex)
        candidate = rejectedIndex(i);
        delta = selected-scaled(candidate,:);
        distance(candidate) = min(sqrt(sum(delta.^2,2)))/ ...
            sqrt(dimension);
    end
end

function [highMask,maxMask] = disagreementSets( ...
    disagreement,indicatorPercentile,relationPercentile,coarseKept)
    candidateCount = numel(coarseKept);
    highMask = false(candidateCount,1);
    maxMask = false(candidateCount,1);
    if any(~isfinite(disagreement))
        return;
    end
    rejected = find(~coarseKept);
    if isempty(rejected)
        return;
    end
    tieTolerance = 1e-12;
    disagreementKey = round(disagreement(rejected)/tieTolerance)* ...
        tieTolerance;
    keys = [-disagreementKey, ...
        -indicatorPercentile(rejected), ...
        relationPercentile(rejected),rejected];
    [~,localOrder] = sortrows(keys,[1 2 3 4]);
    ordered = rejected(localOrder);
    highCount = ceil(0.20*numel(rejected));
    high = ordered(1:highCount);
    high = high(disagreement(high) > 0);
    highMask(high) = true;
    if disagreement(ordered(1)) > 0
        maxMask(ordered(1)) = true;
    end
end

function validateInputs(run,generation,fe,progress,candidateMode, ...
    trace,shadow,counterfactual,cvKendall,audit)
    if ~validIntegerScalar(run) || run < 1 || ...
            ~validIntegerScalar(generation) || generation < 0 || ...
            ~validIntegerScalar(fe) || fe < 0 || ...
            ~validFiniteScalar(progress) || ...
            ~validFiniteScalar(candidateMode)
        invalid('Run metadata must contain finite real scalar values.');
    end
    validModes = [audit.codes.candidateMode.unknown, ...
        audit.codes.candidateMode.explore, ...
        audit.codes.candidateMode.indicator];
    if ~ismember(candidateMode,validModes)
        invalid('CandidateMode is not a CascadeAuditSchema code.');
    end
    if ~validOptionalFiniteScalar(cvKendall) || ...
            (isfinite(cvKendall) && abs(cvKendall) > 1)
        invalid('CVKendall must be NaN or a finite value in [-1,1].');
    end

    traceFields = {'CandidateDecisions','Lower','Upper', ...
        'RelationScore','IndicatorScore','CoarseKept','SelectedMask', ...
        'OperationalIndicatorUsed'};
    requireFields(trace,traceFields,'trace');
    if ~validFiniteMatrix(trace.CandidateDecisions) || ...
            isempty(trace.CandidateDecisions) || ...
            size(trace.CandidateDecisions,2) < 1
        invalid('Candidate decisions must be a nonempty finite matrix.');
    end
    candidateCount = size(trace.CandidateDecisions,1);
    dimension = size(trace.CandidateDecisions,2);
    if ~validFiniteVector(trace.Lower,dimension) || ...
            ~validFiniteVector(trace.Upper,dimension) || ...
            any(trace.Upper(:) <= trace.Lower(:))
        invalid('Decision bounds must be finite, compatible, and ordered.');
    end
    if ~validFiniteVector(trace.RelationScore,candidateCount) || ...
            ~validNaNVector(trace.IndicatorScore,candidateCount) || ...
            ~validMask(trace.CoarseKept,candidateCount) || ...
            ~validMask(trace.SelectedMask,candidateCount) || ...
            ~validFlag(trace.OperationalIndicatorUsed)
        invalid('Trace vectors must match the candidate count.');
    end
    coarseKept = logical(trace.CoarseKept(:));
    selectedMask = logical(trace.SelectedMask(:));
    if ~any(selectedMask) || any(selectedMask & ~coarseKept)
        invalid('Selected candidates must be a nonempty subset of coarse.');
    end
    if logical(trace.OperationalIndicatorUsed) && ...
            any(~isfinite(trace.IndicatorScore(:)))
        invalid(['Operational indicator use requires finite full-pool ', ...
            'indicator scores.']);
    end

    shadowFields = {'CandidateObjectives','CandidateConstraints', ...
        'FeasibleMask','MarginalIGDp','BaselineIGDp', ...
        'BaselineDistance','CandidateDistance','ReferenceCount', ...
        'ShadowEvaluationCount'};
    requireFields(shadow,shadowFields,'shadow');
    if ~validFiniteMatrix(shadow.CandidateObjectives) || ...
            size(shadow.CandidateObjectives,1) ~= candidateCount || ...
            size(shadow.CandidateObjectives,2) < 1 || ...
            ~validFiniteMatrix(shadow.CandidateConstraints) || ...
            size(shadow.CandidateConstraints,1) ~= candidateCount || ...
            ~validMask(shadow.FeasibleMask,candidateCount) || ...
            ~validFiniteVector(shadow.MarginalIGDp,candidateCount) || ...
            any(shadow.MarginalIGDp(:) < 0) || ...
            ~validFiniteScalar(shadow.BaselineIGDp) || ...
            shadow.BaselineIGDp < 0
        invalid('Shadow candidate data must be finite and compatible.');
    end
    if ~validFiniteVector(shadow.BaselineDistance,[]) || ...
            isempty(shadow.BaselineDistance) || ...
            any(shadow.BaselineDistance(:) < 0) || ...
            ~validFiniteMatrix(shadow.CandidateDistance) || ...
            size(shadow.CandidateDistance,2) ~= candidateCount || ...
            any(shadow.CandidateDistance(:) < 0) || ...
            ~validIntegerScalar(shadow.ReferenceCount) || ...
            shadow.ReferenceCount < 1 || ...
            numel(shadow.BaselineDistance) ~= shadow.ReferenceCount || ...
            size(shadow.CandidateDistance,1) ~= shadow.ReferenceCount || ...
            ~validIntegerScalar(shadow.ShadowEvaluationCount) || ...
            shadow.ShadowEvaluationCount ~= candidateCount
        invalid('Shadow IGD+ distances and counts are inconsistent.');
    end

    counterfactualFields = {'BatchSize','DisplacedIndex', ...
        'BaselineBatchIGDp','BaselineBatchUtility','ReplacementGain', ...
        'GreedyAllIndices','GreedyCoarseIndices','GreedyAllUtility', ...
        'GreedyCoarseUtility','NormalizedBatchCoverageRegret', ...
        'HasBatchCoverageOpportunity','OracleRejectedReplacementGain', ...
        'OracleRejectedIndex','HasReplacementOpportunity'};
    requireFields(counterfactual,counterfactualFields,'counterfactual');
    if ~validIntegerScalar(counterfactual.BatchSize) || ...
            counterfactual.BatchSize ~= nnz(selectedMask) || ...
            counterfactual.BatchSize < 1 || ...
            counterfactual.BatchSize > candidateCount || ...
            ~validOptionalIndex(counterfactual.DisplacedIndex, ...
                candidateCount) || ...
            ~validFiniteScalar(counterfactual.BaselineBatchIGDp) || ...
            counterfactual.BaselineBatchIGDp < 0 || ...
            ~validFiniteScalar(counterfactual.BaselineBatchUtility) || ...
            counterfactual.BaselineBatchUtility < 0 || ...
            ~validNaNVector(counterfactual.ReplacementGain, ...
                candidateCount)
        invalid('Counterfactual batch data are invalid or incompatible.');
    end
    if isfinite(counterfactual.DisplacedIndex) && ...
            ~selectedMask(counterfactual.DisplacedIndex)
        invalid('The displaced candidate must be baseline-selected.');
    end
    replacementGain = counterfactual.ReplacementGain(:);
    rejectedGain = replacementGain(~coarseKept);
    if any(~isnan(replacementGain(coarseKept))) || ...
            (~isempty(rejectedGain) && ...
            ~(all(isfinite(rejectedGain)) || all(isnan(rejectedGain))))
        invalid(['Replacement gain must be NaN for coarse candidates and ', ...
            'uniformly known or unknown for rejected candidates.']);
    end
    batchSize = counterfactual.BatchSize;
    if ~validIndexVector(counterfactual.GreedyAllIndices, ...
            batchSize,candidateCount) || ...
            ~validIndexVector(counterfactual.GreedyCoarseIndices, ...
                batchSize,candidateCount) || ...
            any(~coarseKept(counterfactual.GreedyCoarseIndices(:))) || ...
            ~validFiniteScalar(counterfactual.GreedyAllUtility) || ...
            counterfactual.GreedyAllUtility < 0 || ...
            ~validFiniteScalar(counterfactual.GreedyCoarseUtility) || ...
            counterfactual.GreedyCoarseUtility < 0 || ...
            ~validOptionalUnitScalar( ...
                counterfactual.NormalizedBatchCoverageRegret) || ...
            ~validFlag(counterfactual.HasBatchCoverageOpportunity) || ...
            ~validFiniteScalar( ...
                counterfactual.OracleRejectedReplacementGain) || ...
            ~validOptionalIndex(counterfactual.OracleRejectedIndex, ...
                candidateCount) || ...
            ~validFlag(counterfactual.HasReplacementOpportunity)
        invalid('Counterfactual metrics are malformed or nonfinite.');
    end
    if logical(counterfactual.HasBatchCoverageOpportunity) ~= ...
            isfinite(counterfactual.NormalizedBatchCoverageRegret)
        invalid('Batch-opportunity flag and normalized regret disagree.');
    end
    if isfinite(counterfactual.OracleRejectedIndex) && ...
            coarseKept(counterfactual.OracleRejectedIndex)
        invalid('The oracle replacement candidate must be rejected.');
    end
end

function requireFields(value,names,label)
    if ~isstruct(value) || ~isscalar(value) || ...
            ~all(isfield(value,names))
        invalid(['Missing or malformed ',label,' audit structure.']);
    end
end

function valid = validFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
        isfinite(value);
end

function valid = validIntegerScalar(value)
    valid = validFiniteScalar(value) && value == fix(value);
end

function valid = validOptionalFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
        (isfinite(value) || isnan(value));
end

function valid = validOptionalUnitScalar(value)
    valid = validOptionalFiniteScalar(value) && ...
        (isnan(value) || (value >= 0 && value <= 1));
end

function valid = validOptionalIndex(value,count)
    valid = validOptionalFiniteScalar(value) && ...
        (isnan(value) || (value == fix(value) && value >= 1 && ...
        value <= count));
end

function valid = validFiniteMatrix(value)
    valid = isnumeric(value) && isreal(value) && ismatrix(value) && ...
        all(isfinite(value(:)));
end

function valid = validFiniteVector(value,count)
    valid = isnumeric(value) && isreal(value) && isvector(value) && ...
        all(isfinite(value(:)));
    if valid && ~isempty(count)
        valid = numel(value) == count;
    end
end

function valid = validNaNVector(value,count)
    valid = isnumeric(value) && isreal(value) && isvector(value) && ...
        numel(value) == count && all(~isinf(value(:)));
end

function valid = validMask(value,count)
    valid = (islogical(value) || isnumeric(value)) && isreal(value) && ...
        isvector(value) && numel(value) == count && ...
        all(isfinite(double(value(:)))) && ...
        all(ismember(double(value(:)),[0 1]));
end

function valid = validFlag(value)
    valid = validMask(value,1);
end

function valid = validIndexVector(value,expectedCount,candidateCount)
    valid = isnumeric(value) && isreal(value) && isvector(value) && ...
        numel(value) == expectedCount && all(isfinite(value(:))) && ...
        all(value(:) == fix(value(:))) && all(value(:) >= 1) && ...
        all(value(:) <= candidateCount) && ...
        numel(unique(value(:))) == expectedCount;
end

function index = column(audit,tableName,columnName)
    index = find(strcmp(audit.columns.(tableName),columnName),1);
    if isempty(index)
        invalid('CascadeAuditSchema is missing a required column.');
    end
end

function invalid(message)
    error('AdaMaO:InvalidCascadeAuditRows','%s',message);
end
