function audit = CascadeAuditSchema()
%CascadeAuditSchema - Versioned numeric contract for cascade auditing.

    audit.version = 1;
    audit.columns.candidateRows = { ...
        'Run','Generation','FE','PostInitProgress','CandidateIndex', ...
        'CandidateMode','OperationalIndicatorUsed', ...
        'RelationScore','RelationPercentile','IndicatorScore', ...
        'IndicatorPercentile','PositiveDisagreement','CoarseKept', ...
        'BaselineSelected','ShadowFeasible','MarginalIGDp','Useful', ...
        'ReplacementGain','NearestSelectedDistance','OracleTopK', ...
        'IndicatorTopK','MaxPositiveDisagreement'};
    audit.columns.generationRows = { ...
        'Run','Generation','FE','PostInitProgress','CandidateMode', ...
        'OperationalIndicatorUsed', ...
        'CandidateCount','CoarseCount','BatchSize','ReferenceCount', ...
        'ShadowEvaluationCount','BaselineIGDp','RecallAtK','UsefulFNR', ...
        'SingleCoverageRegret','NormalizedBatchCoverageRegret', ...
        'RescueOpportunityRate','DisagreementEnrichment','CVKendall', ...
        'MaxDisagreementReplacementGain','MaxDisagreementSuccess', ...
        'OracleRejectedReplacementGain','ReplacementCapture', ...
        'BaselineBatchUtility','IndicatorTopKMeanUtility', ...
        'FullReferenceRankCorrelation','FullReferenceTopKOverlap', ...
        'AuditSeconds'};
    audit.codes.candidateMode.unknown   = 0;
    audit.codes.candidateMode.explore   = 1;
    audit.codes.candidateMode.indicator = 2;
    audit.candidateRows  = zeros(0,numel(audit.columns.candidateRows));
    audit.generationRows = zeros(0,numel(audit.columns.generationRows));
    audit.totalShadowEvaluations = 0;
    audit.totalAuditSeconds = 0;
end
