function [networkRows,candidateRows] = ...
    CompleteSDEConfidenceCandidateAudit( ...
    networkRows,candidateEvalIDs,candidateObj,candidateCon, ...
    anchorEvalIDs,anchorObj,anchorCon,optimum,lp,varargin)
%CompleteSDEConfidenceCandidateAudit Add objective truth after evaluation.

    probe = SDEConfidenceProbeSchema();
    options = parseOptions(probe,anchorEvalIDs,anchorObj,anchorCon,varargin{:});
    [candidateEvalIDs,candidateObj,candidateCon,anchorEvalIDs, ...
        anchorObj,anchorCon,optimum,options] = validateInputs( ...
        probe,networkRows,candidateEvalIDs,candidateObj,candidateCon, ...
        anchorEvalIDs,anchorObj,anchorCon,optimum,lp,options);

    candidateIDColumn = col(probe,'networkPairRows','CandidateEvalID');
    anchorIDColumn = col(probe,'networkPairRows','AnchorEvalID');
    [candidateFound,candidateIndex] = ismember( ...
        networkRows(:,candidateIDColumn),candidateEvalIDs);
    [anchorFound,anchorIndex] = ismember( ...
        networkRows(:,anchorIDColumn),anchorEvalIDs);
    if ~all(candidateFound) || ~all(anchorFound)
        error('AdaMaO:InvalidConfidenceCandidateAudit', ...
            'Network rows reference an unknown candidate or anchor.');
    end

    networkRows(:,col(probe,'networkPairRows','ParetoRelation')) = ...
        SDEConfidenceTrueRelation( ...
        candidateObj(candidateIndex,:),anchorObj(anchorIndex,:), ...
        candidateCon(candidateIndex,:),anchorCon(anchorIndex,:), ...
        options.Tolerance);

    combinedFitness = calFitness_SDE([anchorObj;candidateObj],lp);
    anchorFitness = combinedFitness(1:size(anchorObj,1));
    candidateFitness = combinedFitness(size(anchorObj,1)+1:end);
    networkRows(:,col(probe,'networkPairRows','SDERelation')) = ...
        compareScores(candidateFitness(candidateIndex), ...
        anchorFitness(anchorIndex),options.Tolerance);

    nCandidate = numel(candidateEvalIDs);
    candidateRows = nan(nCandidate, ...
        numel(probe.columns.candidateRows));
    candidateRows(:,col(probe,'candidateRows','EvalID')) = ...
        candidateEvalIDs;
    candidateRows(:,col(probe,'candidateRows','RelationMode')) = ...
        options.RelationMode;
    candidateRows(:,col(probe,'candidateRows','CandidateMode')) = ...
        options.CandidateMode;

    anchorND = feasibilityFirstNondominated( ...
        anchorObj,anchorCon,options.Tolerance);
    currentNDObj = anchorObj(anchorND,:);
    currentNDCon = anchorCon(anchorND,:);
    baselineDistance = pdist2(optimum,currentNDObj);
    baselineIGD = mean(min(baselineDistance,[],2));
    predictedColumn = col(probe,'networkPairRows','PredictedRelation');
    confidenceColumn = col(probe,'networkPairRows','NetworkConfidence');
    generationColumn = col(probe,'networkPairRows','Generation');
    feColumn = col(probe,'networkPairRows','FE');

    for i = 1:nCandidate
        rowMask = networkRows(:,candidateIDColumn) == candidateEvalIDs(i);
        if ~any(rowMask)
            error('AdaMaO:InvalidConfidenceCandidateAudit', ...
                'Every evaluated candidate must have network audit rows.');
        end
        generations = unique(networkRows(rowMask,generationColumn));
        predictionFE = unique(networkRows(rowMask,feColumn));
        if numel(generations) ~= 1 || numel(predictionFE) ~= 1
            error('AdaMaO:InvalidConfidenceCandidateAudit', ...
                'Candidate network rows disagree on generation or FE.');
        end
        candidateRows(i,col(probe,'candidateRows','Generation')) = ...
            generations;
        candidateRows(i,col(probe,'candidateRows','FE')) = predictionFE;
        candidateRows(i,col(probe,'candidateRows','NetworkConfidence')) = ...
            mean(networkRows(rowMask,confidenceColumn));
        candidateRows(i,col(probe,'candidateRows', ...
            'PredictedBetterRate')) = ...
            mean(networkRows(rowMask,predictedColumn) == 1);

        relation = SDEConfidenceTrueRelation( ...
            repmat(candidateObj(i,:),size(anchorObj,1),1),anchorObj, ...
            repmat(candidateCon(i,:),size(anchorCon,1),1),anchorCon, ...
            options.Tolerance);
        candidateRows(i,col(probe,'candidateRows','DominatesAny')) = ...
            any(relation == 1);
        candidateRows(i,col(probe,'candidateRows','DominatedByAny')) = ...
            any(relation == -1);
        candidateRows(i,col(probe,'candidateRows','IsNondominated')) = ...
            ~any(relation == -1);

        relationToND = SDEConfidenceTrueRelation( ...
            repmat(candidateObj(i,:),size(currentNDObj,1),1), ...
            currentNDObj,repmat(candidateCon(i,:), ...
            size(currentNDCon,1),1),currentNDCon,options.Tolerance);
        if any(relationToND == -1)
            marginalIGD = 0;
        else
            keep = relationToND ~= 1;
            candidateDistance = pdist2(optimum,candidateObj(i,:));
            updatedDistance = [baselineDistance(:,keep),candidateDistance];
            marginalIGD = baselineIGD - mean(min(updatedDistance,[],2));
        end
        candidateRows(i,col(probe,'candidateRows','MarginalIGD')) = ...
            marginalIGD;
        candidateRows(i,col(probe,'candidateRows', ...
            'MarginalIGDPositive')) = marginalIGD > options.Tolerance;
    end

    historyObj = options.HistoryObjectives;
    historyCon = options.HistoryConstraints;
    archiveND = feasibilityFirstNondominated( ...
        [historyObj;candidateObj],[historyCon;candidateCon], ...
        options.Tolerance);
    candidateRows(:,col(probe,'candidateRows','ArchiveNDNext')) = ...
        double(archiveND(size(historyObj,1)+1:end));
end

function options = parseOptions(probe,anchorIDs,anchorObj,anchorCon,varargin)
    options.RelationMode = probe.codes.relationMode.unknown;
    options.CandidateMode = probe.codes.candidateMode.unknown;
    options.Tolerance = 1e-12;
    options.HistoryEvalIDs = anchorIDs;
    options.HistoryObjectives = anchorObj;
    options.HistoryConstraints = anchorCon;
    if mod(numel(varargin),2) ~= 0
        error('AdaMaO:InvalidConfidenceAuditOption', ...
            'Candidate audit options must be name-value pairs.');
    end
    allowed = {'RelationMode','CandidateMode','Tolerance', ...
        'HistoryEvalIDs','HistoryObjectives','HistoryConstraints'};
    for i = 1:2:numel(varargin)
        name = validatestring(varargin{i},allowed);
        options.(name) = varargin{i+1};
    end
end

function [candidateIDs,candidateObj,candidateCon,anchorIDs,anchorObj, ...
    anchorCon,optimum,options] = validateInputs( ...
    probe,networkRows,candidateIDs,candidateObj,candidateCon,anchorIDs, ...
    anchorObj,anchorCon,optimum,lp,options)
    candidateIDs = candidateIDs(:);
    anchorIDs = anchorIDs(:);
    options.HistoryEvalIDs = options.HistoryEvalIDs(:);
    nCandidate = numel(candidateIDs);
    nAnchor = numel(anchorIDs);
    if isempty(candidateCon)
        candidateCon = zeros(nCandidate,0);
    end
    if isempty(anchorCon)
        anchorCon = zeros(nAnchor,0);
    end
    if isempty(options.HistoryConstraints)
        options.HistoryConstraints = zeros( ...
            size(options.HistoryObjectives,1),size(anchorCon,2));
    end
    numericMatrix = @(x) isnumeric(x) && isreal(x) && ismatrix(x) && ...
        all(isfinite(x(:)));
    validCandidateIDs = validPositiveIntegerIDs(candidateIDs,true);
    validAnchorIDs = validPositiveIntegerIDs(anchorIDs,true);
    validHistoryIDs = validPositiveIntegerIDs( ...
        options.HistoryEvalIDs,true);
    validNetworkRows = validCandidateIDs && validAnchorIDs && ...
        networkRowsAreComplete( ...
        probe,networkRows,candidateIDs,anchorIDs);
    validHistoryMatrices = ...
        numel(options.HistoryEvalIDs) == ...
        size(options.HistoryObjectives,1) && ...
        numericMatrix(options.HistoryObjectives) && ...
        size(options.HistoryObjectives,2) == size(anchorObj,2) && ...
        numericMatrix(options.HistoryConstraints) && ...
        size(options.HistoryConstraints,1) == ...
        size(options.HistoryObjectives,1) && ...
        size(options.HistoryConstraints,2) == size(anchorCon,2);
    matchingAnchorData = false;
    if validHistoryIDs && validHistoryMatrices
        [anchorsInHistory,historyLocation] = ismember( ...
            anchorIDs,options.HistoryEvalIDs);
        matchingAnchorData = all(anchorsInHistory);
    end
    if matchingAnchorData
        matchingAnchorData = isequal( ...
            options.HistoryObjectives(historyLocation,:),anchorObj) && ...
            isequal(options.HistoryConstraints(historyLocation,:),anchorCon);
    end
    valid = validNetworkRows && ...
        isempty(intersect(candidateIDs,anchorIDs)) && ...
        numericMatrix(candidateObj) && size(candidateObj,1) == nCandidate && ...
        numericMatrix(anchorObj) && size(anchorObj,1) == nAnchor && ...
        size(candidateObj,2) == size(anchorObj,2) && ...
        size(candidateObj,2) > 0 && numericMatrix(candidateCon) && ...
        size(candidateCon,1) == nCandidate && numericMatrix(anchorCon) && ...
        size(anchorCon,1) == nAnchor && ...
        size(candidateCon,2) == size(anchorCon,2) && ...
        numericMatrix(optimum) && size(optimum,1) > 0 && ...
        size(optimum,2) == size(anchorObj,2) && isnumeric(lp) && ...
        isreal(lp) && isscalar(lp) && isfinite(lp) && lp > 0 && ...
        isnumeric(options.Tolerance) && isscalar(options.Tolerance) && ...
        isfinite(options.Tolerance) && options.Tolerance >= 0 && ...
        validHistoryIDs && ...
        validHistoryMatrices && ...
        matchingAnchorData && ...
        isempty(intersect(candidateIDs,options.HistoryEvalIDs));
    if ~valid
        error('AdaMaO:InvalidConfidenceCandidateAudit', ...
            'Candidate completion inputs are inconsistent or nonfinite.');
    end
end

function valid = networkRowsAreComplete( ...
    probe,networkRows,candidateIDs,anchorIDs)
    requiredColumns = [ ...
        col(probe,'networkPairRows','Generation'), ...
        col(probe,'networkPairRows','FE'), ...
        col(probe,'networkPairRows','CandidateEvalID'), ...
        col(probe,'networkPairRows','AnchorEvalID'), ...
        col(probe,'networkPairRows','AnchorCatalog'), ...
        col(probe,'networkPairRows','PredictedRelation'), ...
        col(probe,'networkPairRows','ProbabilityLeftBetter'), ...
        col(probe,'networkPairRows','ProbabilitySame'), ...
        col(probe,'networkPairRows','ProbabilityRightBetter'), ...
        col(probe,'networkPairRows','NetworkConfidence')];
    valid = isnumeric(networkRows) && isreal(networkRows) && ...
        ismatrix(networkRows) && ...
        size(networkRows,2) == numel(probe.columns.networkPairRows) && ...
        all(isfinite(networkRows(:,requiredColumns)),'all') && ...
        ~any(isinf(networkRows(:)));
    if ~valid
        return;
    end

    candidateColumn = col(probe,'networkPairRows','CandidateEvalID');
    anchorColumn = col(probe,'networkPairRows','AnchorEvalID');
    actualPairs = networkRows(:,[candidateColumn,anchorColumn]);
    expectedPairs = [ ...
        repelem(candidateIDs(:),numel(anchorIDs),1), ...
        repmat(anchorIDs,numel(candidateIDs),1)];
    valid = validPositiveIntegerIDs(actualPairs(:,1),false) && ...
        validPositiveIntegerIDs(actualPairs(:,2),false) && ...
        isequal(sortrows(actualPairs,[1 2]), ...
        sortrows(expectedPairs,[1 2]));
    if ~valid
        return;
    end

    probabilityColumns = [ ...
        col(probe,'networkPairRows','ProbabilityLeftBetter'), ...
        col(probe,'networkPairRows','ProbabilitySame'), ...
        col(probe,'networkPairRows','ProbabilityRightBetter')];
    probabilities = networkRows(:,probabilityColumns);
    confidence = networkRows(:, ...
        col(probe,'networkPairRows','NetworkConfidence'));
    predicted = networkRows(:, ...
        col(probe,'networkPairRows','PredictedRelation'));
    anchorCatalog = networkRows(:, ...
        col(probe,'networkPairRows','AnchorCatalog'));
    tolerance = 1e-10;
    [maximumProbability,classIndex] = max(probabilities,[],2);
    relationCodes = [1;0;-1];
    expectedRelation = relationCodes(classIndex);
    valid = all(probabilities(:) >= 0 & probabilities(:) <= 1) && ...
        all(abs(sum(probabilities,2)-1) <= tolerance) && ...
        all(abs(confidence-maximumProbability) <= tolerance) && ...
        isequal(predicted,expectedRelation) && ...
        all(anchorCatalog == 0 | anchorCatalog == 1);
end

function valid = validPositiveIntegerIDs(ids,requireUnique)
    valid = isnumeric(ids) && isreal(ids) && ...
        (isempty(ids) || isvector(ids)) && all(isfinite(ids)) && ...
        all(ids > 0) && all(ids == floor(ids));
    if valid && requireUnique
        valid = numel(unique(ids)) == numel(ids);
    end
end

function relation = compareScores(left,right,tolerance)
    relation = zeros(size(left));
    relation(left > right + tolerance) = 1;
    relation(right > left + tolerance) = -1;
end

function mask = feasibilityFirstNondominated(objectives,constraints,tolerance)
    n = size(objectives,1);
    mask = true(n,1);
    for i = 1:n
        other = [1:i-1,i+1:n];
        if isempty(other)
            continue;
        end
        relation = SDEConfidenceTrueRelation( ...
            objectives(other,:),repmat(objectives(i,:),n-1,1), ...
            constraints(other,:),repmat(constraints(i,:),n-1,1), ...
            tolerance);
        mask(i) = ~any(relation == 1);
    end
end

function index = col(probe,rowName,columnName)
    index = find(strcmp(probe.columns.(rowName),columnName),1);
end
