function result = ComputeCascadeBatchCounterfactual( ...
    baselineDistance,candidateDistance,selectedMask,coarseMask, ...
    indicatorScore)
%ComputeCascadeBatchCounterfactual - Fixed-budget batch IGD+ diagnostics.
%
% The operational batch is kept fixed. Every relation-rejected candidate
% is tested by replacing the selected candidate having the lowest finite
% indicator score. Greedy all/coarse utilities diagnose batch coverage.

    [baselineDistance,candidateDistance,selectedMask,coarseMask, ...
        indicatorScore] = validateInputs(baselineDistance, ...
        candidateDistance,selectedMask,coarseMask,indicatorScore);
    candidateCount = size(candidateDistance,2);
    batchSize = nnz(selectedMask);
    baselineIGDp = mean(baselineDistance);
    tolerance = max(1e-12,1e-10*max(1,abs(baselineIGDp)));

    selectedDistance = candidateDistance(:,selectedMask);
    baselineBatchDistance = min(baselineDistance, ...
        min(selectedDistance,[],2));
    baselineBatchIGDp = mean(baselineBatchDistance);
    replacementTolerance = max(1e-12, ...
        1e-10*max(1,abs(baselineBatchIGDp)));

    result.BatchSize = batchSize;
    result.DisplacedIndex = NaN;
    result.BaselineBatchIGDp = baselineBatchIGDp;
    result.BaselineBatchUtility = baselineIGDp-baselineBatchIGDp;
    result.ReplacementGain = NaN(candidateCount,1);

    selectedIndex = find(selectedMask);
    if ~isempty(selectedIndex)
        selectedScores = indicatorScore(selectedIndex);
        minimumScore = min(selectedScores);
        displaced = selectedIndex(find(selectedScores == minimumScore,1));
        result.DisplacedIndex = displaced;
        remainingMask = selectedMask;
        remainingMask(displaced) = false;
        replacementBaseDistance = baselineDistance;
        if any(remainingMask)
            replacementBaseDistance = min(replacementBaseDistance, ...
                min(candidateDistance(:,remainingMask),[],2));
        end
        rejectedIndex = find(~coarseMask);
        for i = 1:numel(rejectedIndex)
            candidate = rejectedIndex(i);
            replacementDistance = min(replacementBaseDistance, ...
                candidateDistance(:,candidate));
            result.ReplacementGain(candidate) = baselineBatchIGDp - ...
                mean(replacementDistance);
        end
    end

    [result.GreedyAllIndices,result.GreedyAllUtility] = ...
        greedyUtility(baselineDistance,candidateDistance, ...
        true(candidateCount,1),batchSize);
    [result.GreedyCoarseIndices,result.GreedyCoarseUtility] = ...
        greedyUtility(baselineDistance,candidateDistance, ...
        coarseMask,batchSize);

    result.HasBatchCoverageOpportunity = ...
        result.GreedyAllUtility > tolerance;
    if result.HasBatchCoverageOpportunity
        result.NormalizedBatchCoverageRegret = max(0, ...
            1-result.GreedyCoarseUtility/result.GreedyAllUtility);
    else
        result.NormalizedBatchCoverageRegret = NaN;
    end

    rejectedGain = result.ReplacementGain(~coarseMask);
    rejectedGain = rejectedGain(isfinite(rejectedGain));
    if isempty(rejectedGain)
        result.OracleRejectedReplacementGain = 0;
        result.OracleRejectedIndex = NaN;
    else
        result.OracleRejectedReplacementGain = max(rejectedGain);
        rejectedIndex = find(~coarseMask & isfinite(result.ReplacementGain));
        result.OracleRejectedIndex = rejectedIndex(find( ...
            result.ReplacementGain(rejectedIndex) == ...
            result.OracleRejectedReplacementGain,1));
    end
    result.HasReplacementOpportunity = ...
        result.OracleRejectedReplacementGain > replacementTolerance;
end

function [indices,utility] = greedyUtility( ...
    baselineDistance,candidateDistance,allowedMask,batchSize)
    allowed = find(allowedMask);
    take = min(batchSize,numel(allowed));
    indices = zeros(take,1);
    currentDistance = baselineDistance;
    baselineIGDp = mean(baselineDistance);
    for slot = 1:take
        gains = mean(max(currentDistance- ...
            candidateDistance(:,allowed),0),1);
        [~,localIndex] = max(gains);
        chosen = allowed(localIndex);
        indices(slot) = chosen;
        currentDistance = min(currentDistance, ...
            candidateDistance(:,chosen));
        allowed(localIndex) = [];
    end
    utility = max(0,baselineIGDp-mean(currentDistance));
end

function [baselineDistance,candidateDistance,selectedMask,coarseMask, ...
    indicatorScore] = validateInputs(baselineDistance,candidateDistance, ...
    selectedMask,coarseMask,indicatorScore)
    if ~isnumeric(baselineDistance) || ~isreal(baselineDistance) || ...
            ~isvector(baselineDistance) || isempty(baselineDistance) || ...
            any(~isfinite(baselineDistance(:))) || ...
            any(baselineDistance(:) < 0) || ...
            ~isnumeric(candidateDistance) || ~isreal(candidateDistance) || ...
            ~ismatrix(candidateDistance) || ...
            any(~isfinite(candidateDistance(:))) || ...
            any(candidateDistance(:) < 0) || ...
            size(candidateDistance,1) ~= numel(baselineDistance) || ...
            size(candidateDistance,2) < 1
        error('AdaMaO:InvalidCascadeBatchInputs', ...
            'IGD+ distances must be finite, nonnegative, and compatible.');
    end
    candidateCount = size(candidateDistance,2);
    if ~validMask(selectedMask,candidateCount) || ...
            ~validMask(coarseMask,candidateCount) || ...
            ~isnumeric(indicatorScore) || ~isreal(indicatorScore) || ...
            ~isvector(indicatorScore) || ...
            numel(indicatorScore) ~= candidateCount || ...
            any(~isfinite(indicatorScore(:))) || ...
            nnz(selectedMask) < 1 || any(selectedMask(:) & ~coarseMask(:))
        error('AdaMaO:InvalidCascadeBatchInputs', ...
            ['Selection/coarse masks and indicator scores must match the ', ...
            'candidate count, and selected candidates must be coarse-kept.']);
    end
    baselineDistance = baselineDistance(:);
    selectedMask = logical(selectedMask(:));
    coarseMask = logical(coarseMask(:));
    indicatorScore = indicatorScore(:);
end

function valid = validMask(mask,count)
    valid = (islogical(mask) || isnumeric(mask)) && isreal(mask) && ...
        isvector(mask) && numel(mask) == count && ...
        all(isfinite(double(mask(:)))) && ...
        all(ismember(double(mask(:)),[0 1]));
end
