function rows = PredictSDEConfidenceCandidatePairs( ...
    generation,fe,candidateEvalIDs,candidateDecs,anchorEvalIDs, ...
    anchorDecs,anchorCatalog,model)
%PredictSDEConfidenceCandidatePairs Audit candidate-first network outputs.

    probe = SDEConfidenceProbeSchema();
    [candidateEvalIDs,candidateDecs,anchorEvalIDs,anchorDecs, ...
        anchorCatalog] = validateInputs(generation,fe,candidateEvalIDs, ...
        candidateDecs,anchorEvalIDs,anchorDecs,anchorCatalog,model);
    nCandidate = numel(candidateEvalIDs);
    nAnchor = numel(anchorEvalIDs);
    if nCandidate == 0 || nAnchor == 0
        rows = zeros(0,numel(probe.columns.networkPairRows));
        return;
    end

    candidateIndex = repelem((1:nCandidate)',nAnchor);
    anchorIndex = repmat((1:nAnchor)',nCandidate,1);
    pairInput = [candidateDecs(candidateIndex,:), ...
        anchorDecs(anchorIndex,:)];
    normalizedInput = mapminmax('apply',pairInput',model.mp_struct);
    probabilities = model.net(normalizedInput)';
    if ~isnumeric(probabilities) || ~isreal(probabilities) || ...
            ~isequal(size(probabilities),[numel(candidateIndex),3]) || ...
            any(~isfinite(probabilities(:))) || ...
            any(probabilities(:) < 0)
        error('AdaMaO:InvalidConfidenceNetworkOutput', ...
            'The relation network must return finite nonnegative 3-class rows.');
    end
    rowSum = sum(probabilities,2);
    if any(rowSum <= 0)
        error('AdaMaO:InvalidConfidenceNetworkOutput', ...
            'Each relation-network output row must have positive mass.');
    end
    probabilities = probabilities./rowSum;
    [networkConfidence,classIndex] = max(probabilities,[],2);
    relationCodes = [1;0;-1];
    predictedRelation = relationCodes(classIndex);

    rows = nan(numel(candidateIndex), ...
        numel(probe.columns.networkPairRows));
    rows(:,col(probe,'Generation')) = generation;
    rows(:,col(probe,'FE')) = fe;
    rows(:,col(probe,'CandidateEvalID')) = ...
        candidateEvalIDs(candidateIndex);
    rows(:,col(probe,'AnchorEvalID')) = anchorEvalIDs(anchorIndex);
    rows(:,col(probe,'AnchorCatalog')) = ...
        double(anchorCatalog(anchorIndex));
    rows(:,col(probe,'PredictedRelation')) = predictedRelation;
    rows(:,col(probe,'ProbabilityLeftBetter')) = probabilities(:,1);
    rows(:,col(probe,'ProbabilitySame')) = probabilities(:,2);
    rows(:,col(probe,'ProbabilityRightBetter')) = probabilities(:,3);
    rows(:,col(probe,'NetworkConfidence')) = networkConfidence;
end

function [candidateEvalIDs,candidateDecs,anchorEvalIDs,anchorDecs, ...
    anchorCatalog] = validateInputs(generation,fe,candidateEvalIDs, ...
    candidateDecs,anchorEvalIDs,anchorDecs,anchorCatalog,model)
    candidateEvalIDs = candidateEvalIDs(:);
    anchorEvalIDs = anchorEvalIDs(:);
    anchorCatalog = anchorCatalog(:);
    nCandidate = numel(candidateEvalIDs);
    nAnchor = numel(anchorEvalIDs);
    scalarOK = @(x) isnumeric(x) && isreal(x) && isscalar(x) && ...
        isfinite(x);
    validModel = isstruct(model) && isscalar(model) && ...
        isfield(model,'net') && isfield(model,'mp_struct') && ...
        ~isempty(model.net) && ~isempty(model.mp_struct);
    validCatalog = islogical(anchorCatalog) || ...
        (isnumeric(anchorCatalog) && isreal(anchorCatalog) && ...
        all(isfinite(anchorCatalog)) && ...
        all(anchorCatalog == 0 | anchorCatalog == 1));
    valid = scalarOK(generation) && generation >= 0 && ...
        generation == floor(generation) && scalarOK(fe) && fe >= 0 && ...
        isnumeric(candidateEvalIDs) && isreal(candidateEvalIDs) && ...
        all(isfinite(candidateEvalIDs)) && all(candidateEvalIDs > 0) && ...
        all(candidateEvalIDs == floor(candidateEvalIDs)) && ...
        numel(unique(candidateEvalIDs)) == nCandidate && ...
        isnumeric(anchorEvalIDs) && isreal(anchorEvalIDs) && ...
        all(isfinite(anchorEvalIDs)) && all(anchorEvalIDs > 0) && ...
        all(anchorEvalIDs == floor(anchorEvalIDs)) && ...
        numel(unique(anchorEvalIDs)) == nAnchor && ...
        isempty(intersect(candidateEvalIDs,anchorEvalIDs)) && ...
        isnumeric(candidateDecs) && isreal(candidateDecs) && ...
        ismatrix(candidateDecs) && size(candidateDecs,1) == nCandidate && ...
        isnumeric(anchorDecs) && isreal(anchorDecs) && ...
        ismatrix(anchorDecs) && size(anchorDecs,1) == nAnchor && ...
        size(candidateDecs,2) == size(anchorDecs,2) && ...
        size(candidateDecs,2) > 0 && all(isfinite(candidateDecs(:))) && ...
        all(isfinite(anchorDecs(:))) && numel(anchorCatalog) == nAnchor && ...
        validCatalog && validModel;
    if ~valid
        error('AdaMaO:InvalidConfidenceCandidatePairs', ...
            'Candidate/anchor prediction inputs are inconsistent.');
    end
    anchorCatalog = logical(anchorCatalog);
end

function index = col(probe,columnName)
    index = find(strcmp(probe.columns.networkPairRows,columnName),1);
end
