function probe = SDEConfidenceProbeSchema()
%SDEConfidenceProbeSchema Create the versioned numeric confidence audit.
%
% Every audit table is a numeric matrix. The corresponding ordered column
% names and categorical codes below are the only schema needed to decode
% those matrices.

    probe.version = 1;
    probe.maxPairsPerType = 300;

    probe.columns.solutionRows = { ...
        'Generation','FE','EvalID','RelationMode','CandidateMode', ...
        'Catalog','PBIConfidence','SDEFitness','CurrentND', ...
        'SurviveH1','SurviveH3','FinalND'};
    probe.columns.pbiPairRows = { ...
        'Generation','FE','LeftEvalID','RightEvalID','PairType', ...
        'PredictedRelation','PairConfidence','ParetoRelation', ...
        'SDERelation','LeftSurviveH1','RightSurviveH1', ...
        'LeftSurviveH3','RightSurviveH3','LeftFinalND','RightFinalND'};
    probe.columns.networkPairRows = { ...
        'Generation','FE','CandidateEvalID','AnchorEvalID', ...
        'AnchorCatalog','PredictedRelation','ProbabilityLeftBetter', ...
        'ProbabilitySame','ProbabilityRightBetter','NetworkConfidence', ...
        'ParetoRelation','SDERelation','CandidateSurviveH1', ...
        'CandidateSurviveH3','CandidateFinalND'};
    probe.columns.candidateRows = { ...
        'Generation','FE','EvalID','RelationMode','CandidateMode', ...
        'NetworkConfidence','PredictedBetterRate','DominatesAny', ...
        'DominatedByAny','IsNondominated','MarginalIGD', ...
        'MarginalIGDPositive','SurviveH1','SurviveH3', ...
        'ArchiveNDNext','FinalND'};

    probe.codes.relation.leftBetter = 1;
    probe.codes.relation.incomparable = 0;
    probe.codes.relation.rightBetter = -1;

    probe.codes.pairType.goodGood = 1;
    probe.codes.pairType.restRest = 2;
    probe.codes.pairType.goodRest = 3;

    probe.codes.relationMode.unknown = 0;
    probe.codes.relationMode.conservative = 1;
    probe.codes.relationMode.curriculum = 2;
    probe.codes.relationMode.weighted = 3;

    probe.codes.candidateMode.unknown = 0;
    probe.codes.candidateMode.explore = 1;
    probe.codes.candidateMode.indicator = 2;

    tableNames = fieldnames(probe.columns);
    for i = 1:numel(tableNames)
        name = tableNames{i};
        probe.(name) = zeros(0,numel(probe.columns.(name)));
    end
end
