classdef MLP_MOO < ALGORITHM
% <2024> <multi/many> <real> <expensive>
% Multi-objective optimization with multi-surrogate scoring (MLP per objective)
    methods
        function main(Algorithm, Problem)
            %% Parameter setting
            gmax = Algorithm.ParameterSet(3000);   % number of solutions generated by surrogate
            
            %% Initialization
            if Problem.D <= 10
                N = 11*Problem.D - 1;
            else
                N = 100;
            end
            PopDec = UniformPoint(N, Problem.D, 'Latin');
            Population = Problem.Evaluation(repmat(Problem.upper-Problem.lower, N, 1) .* PopDec + repmat(Problem.lower, N, 1));
            Archive = Population;
            
            %% Optimization loop
            while Algorithm.NotTerminated(Archive)
                % Train surrogates using all evaluated solutions (Archive)
                [surrogates, dec_min, dec_max, obj_min, obj_max] = TrainMLPs(Archive, Problem.D, Problem.M);
                
                % Generate a large number of candidate solutions using GA
                Candidates = OperatorGA(Problem, [Population.decs; Archive.decs], {1,15,1,5});
                Candidates = unique(Candidates, 'rows');  % remove duplicates
                
                % Predict objectives for candidates
                predObj = zeros(size(Candidates,1), Problem.M);
                for i = 1:Problem.M
                    % Normalize decision variables using training min/max
                    X_norm = (Candidates - dec_min) ./ (dec_max - dec_min);
                    X_norm(isnan(X_norm)) = 0;  % handle constant dimensions
                    % Predict
                    predObj(:,i) = surrogates{i}.predict(X_norm);
                    % Denormalize predicted objectives
                    predObj(:,i) = predObj(:,i) .* (obj_max(i) - obj_min(i)) + obj_min(i);
                end
                
                % Score each candidate using weighted sum (equal weights)
                scores = sum(predObj, 2);
                
                % Select the best n candidates for real evaluation
                n_eval = min(ceil(N/2), size(Candidates,1));
                [~, idx] = sort(scores);
                bestCandidates = Candidates(idx(1:n_eval), :);
                
                % Evaluate selected candidates and add to archive
                if ~isempty(bestCandidates)
                    newPop = Problem.Evaluation(bestCandidates);
                    Archive = [Archive, newPop];
                end
                
                % Environmental selection: keep N best individuals from archive
                PopObj = [Archive.objs];
                FrontNo = NDSort(PopObj, N);
                CrowdDis = CrowdingDistance(PopObj, FrontNo);
                [~, rank] = sortrows([FrontNo', -CrowdDis']);
                Next = rank(1:N);
                Population = Archive(Next);
            end
        end
    end
end